(()=>{
'use strict';
const BUILD='LINK PWA 1.0 · Full Solo · source 4.4/443';
const STORE='link_pwa_fullsolo_443_v3';
const now=()=>Date.now();
const id=(p='id')=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const ago=(t)=>{const d=Math.max(0,Date.now()-Number(t||0)),m=Math.floor(d/60000);return m<1?'now':m<60?`${m}m`:m<1440?`${Math.floor(m/60)}h`:`${Math.floor(m/1440)}d`};
const initials=(n='LINK')=>n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'L';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const fmtTime=(t)=>new Date(t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const fmtDate=(t)=>new Date(t).toLocaleDateString([],{month:'short',day:'numeric'});
const CHAT_THEMES=[
  {id:'default',name:'Default',tier:'free',a:'#0A84FF',b:'#0A84FF',text:'#fff'},
  {id:'red',name:'Red',tier:'free',a:'#FF3B30',b:'#FF3B30',text:'#fff'},
  {id:'green',name:'Green',tier:'plus',a:'#34C759',b:'#34C759',text:'#fff'},
  {id:'race_green',name:'Race Green',tier:'plus',a:'#0C7C4A',b:'#0C7C4A',text:'#fff'},
  {id:'lime_green',name:'Lime Green',tier:'plus',a:'#A8E900',b:'#A8E900',text:'#102000'},
  {id:'bright_red',name:'Bright Red',tier:'plus',a:'#FF1744',b:'#FF1744',text:'#fff'},
  {id:'yellow',name:'Yellow',tier:'plus',a:'#FFD60A',b:'#FFD60A',text:'#1B1600'},
  {id:'cyan_green',name:'Cyan Green',tier:'pro',a:'#00C7BE',b:'#00C7BE',text:'#fff'},
  {id:'cyan_blue',name:'Cyan Blue',tier:'pro',a:'#00A9FF',b:'#00A9FF',text:'#fff'},
  {id:'sunset',name:'Sunset',tier:'pro',a:'#FF2D55',b:'#FF9F0A',text:'#fff'},
  {id:'blue_purple',name:'Blue & Purple',tier:'pro',a:'#0A84FF',b:'#AF52DE',text:'#fff'},
  {id:'gold',name:'Gold',tier:'pro',a:'#E0B83D',b:'#B88713',text:'#1F1600'},
  {id:'monochromatic',name:'Monochromatic',tier:'pro',a:'#111111',b:'#6E6E73',text:'#fff'},
  {id:'sky_blue',name:'Sky Blue (Classic)',tier:'pro',a:'#5AC8FA',b:'#5AC8FA',text:'#062538'},
  {id:'rose_pink',name:'Rose Pink',tier:'pro',a:'#FF6482',b:'#FF6482',text:'#fff'},
  {id:'hot_pink',name:'Hot Pink',tier:'pro',a:'#FF2D95',b:'#FF2D95',text:'#fff'},
  {id:'glamorous_pink',name:'Glamurous Pink',tier:'pro',a:'#FF2D95',b:'#BF5AF2',text:'#fff'},
];
const STATUS_COLORS=['#34C759','#0A84FF','#AF52DE','#FF9F0A','#FF453A','#FF2D55','#30B0C7','#8E8E93','#FFD60A','#64D2FF','#BF5AF2','#30D158'];
const STATUS_EMOJIS=['✨','❤️','🎧','🎮','☕️','✈️','📚','🏋️','🌙','🔥','💎','🪐','🚀','💀','🌹','⚡️','🖤','💜','💙','💚','💛','🧡','🤍','👀'];
const DOUBLE_TAP=['❤️','🔥','😂','😍','🥹','😭','💀','😮','😈','💯','✨','🫶','🤝','👀','⚡️','🖤','💜','💙','💚','💛','🧡','🤍','😮‍💨','🫡'];
const STATUS_GRADIENTS=[
 ['ocean',['#00C6FF','#0072FF']],['aurora',['#00F5A0','#00D9F5','#7C5CFC']],['sunset',['#FF512F','#F09819']],['pink_sky',['#FF5F9E','#FF8FD8']],['purple_rain',['#7F00FF','#E100FF']],['electric',['#00E5FF','#4B6CFF']],['mint',['#43E97B','#38F9D7']],['fire',['#FF3D00','#FFB300']],['berry',['#8E2DE2','#FF416C']],['ice',['#74EBD5','#9FACE6']],['midnight',['#0F2027','#203A43','#2C5364']],['graphite',['#111318','#4A4E57']],['gold_luxe',['#8A6116','#E3BE58','#FFF0AE']],['rose_gold',['#B76E79','#F7C5CC','#C98B98']],['silver',['#7C8491','#E2E5EA','#9DA4AE']],['neon_lime',['#B8FF00','#00F5A0']],['cyber',['#00F0FF','#7B2CFF','#FF2DAA']],['candy',['#FF85C1','#8EA6FF','#75F4D4']],['peach',['#FFB199','#FF0844']],['mango',['#FFE259','#FFA751']],['forest',['#134E5E','#71B280']],['emerald',['#00695C','#00C853']],['lagoon',['#00B4DB','#0083B0']],['royal',['#141E30','#243B55','#415A77']],['violet',['#654EA3','#EAAFC8']],['plum',['#41295A','#AA076B']],['lava',['#93291E','#ED213A']],['cherry',['#EB3349','#F45C43']],['blueberry',['#396AFC','#2948FF']],['sky',['#56CCF2','#2F80ED']],['cotton',['#FBC2EB','#A6C1EE']],['sherbet',['#FBD786','#F7797D']],['watermelon',['#00F260','#F79D00','#F12711']],['ultraviolet',['#5F2C82','#49A09D']],['tokyo',['#FF0080','#7928CA','#2AFADF']],['miami',['#00DBDE','#FC00FF']],['sunrise',['#FFCC70','#C850C0','#4158D0']],['nightclub',['#111','#7F00FF','#FF006E']],['polar',['#E0EAFC','#CFDEF3']],['prism',['#0A84FF','#AF52DE','#FF2D55','#FF9F0A']]
];
const PROFILE_EFFECTS=[
 {id:'none',name:'No effect',price:0,fx:'#8E8E93'},{id:'halo',name:'Electric Halo',price:220,fx:'#00E5FF'},{id:'rose',name:'Rose Aura',price:260,fx:'#FF6482'},{id:'gold',name:'Gold Orbit',price:320,fx:'#E0B83D'},{id:'void',name:'Void Ring',price:340,fx:'#7F00FF'},{id:'pulse',name:'Pulse',price:290,fx:'#FF2D55'},{id:'ice',name:'Ice Crown',price:390,fx:'#74EBD5'},{id:'admin_orbit',name:'Executive Orbit',price:0,fx:'#0A84FF',staff:true},{id:'admin_crown',name:'CEO Crown',price:0,fx:'#FFD60A',staff:true},{id:'admin_aura',name:'Founder Aura',price:0,fx:'#BF5AF2',staff:true}
];
const translations={
 cs:{Feed:'Feed',Discover:'Objevit',Chats:'Chaty',Profile:'Profil',Create:'Vytvořit',Activity:'Aktivita',Settings:'Nastavení','What’s new':'Co je nového',Search:'Hledat','New group':'Nová skupina',Message:'Zpráva',Send:'Odeslat',Reply:'Odpovědět',Save:'Uložit',Close:'Zavřít','LINK Official':'LINK Official','Your profile':'Tvůj profil','People you may know':'Lidé, které můžeš znát','Incoming requests':'Příchozí žádosti','Trending now':'Trendy','Direct + group chats · local solo mode.':'Soukromé i skupinové chaty · lokální solo režim.','No chats yet':'Zatím žádné chaty','Edit profile':'Upravit profil','LINK Settings':'Nastavení LINK','Appearance':'Vzhled','Privacy':'Soukromí','Notifications':'Oznámení','Security':'Zabezpečení','Account':'Účet','Language':'Jazyk','Active status':'Aktivní stav','Custom status':'Vlastní status','Double Tap reaction':'Reakce dvojitým klepnutím','LINK Shop':'LINK Shop','Safety Center':'Centrum bezpečnosti','Local accounts':'Lokální účty'},
 en:{}
};
function t(x){return state.language==='cs'?(translations.cs[x]||x):x}
function icon(name,size=20){const paths={
 feed:'<path d="M4 5h16M4 10h16M4 15h10M4 19h7"/>',discover:'<circle cx="12" cy="12" r="8"/><path d="m15.5 8.5-2 5-5 2 2-5z"/>',plus:'<path d="M12 5v14M5 12h14"/>',chats:'<path d="M5 6h14a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H9l-5 3v-4a2 2 0 0 1-1-1.7V8a2 2 0 0 1 2-2z"/>',profile:'<circle cx="12" cy="8" r="3.5"/><path d="M5 20c.7-4 3.2-6 7-6s6.3 2 7 6"/>',search:'<circle cx="10.5" cy="10.5" r="6"/><path d="m15 15 5 5"/>',bell:'<path d="M7 9a5 5 0 0 1 10 0v4l2 3H5l2-3zM10 19h4"/>',gear:'<circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1A7 7 0 0 0 15 6l-.3-2.6h-4L10.5 6a7 7 0 0 0-1.6 1.1l-2.4-1-2 3.4L6.6 11a7 7 0 0 0 0 2l-2.1 1.5 2 3.4 2.4-1A7 7 0 0 0 10.5 18l.3 2.6h4L15 18a7 7 0 0 0 1.6-1.1l2.4 1 2-3.4-2.1-1.5c.1-.3.1-.7.1-1z"/>',dots:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',heart:'<path d="M20 8c0 5-8 11-8 11S4 13 4 8a4 4 0 0 1 7-2.5A4 4 0 0 1 20 8z"/>',repeat:'<path d="m17 3 3 3-3 3M4 6h16M7 21l-3-3 3-3M20 18H4"/>',comment:'<path d="M5 5h14a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H9l-5 3v-4a2 2 0 0 1-1-1.7V7a2 2 0 0 1 2-2z"/>',bookmark:'<path d="M7 4h10v16l-5-3-5 3z"/>',back:'<path d="m15 5-7 7 7 7"/>',send:'<path d="m4 4 17 8-17 8 3-8zM7 12h14"/>',lock:'<rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V8a4 4 0 0 1 8 0v2"/>',palette:'<circle cx="12" cy="12" r="9"/><circle cx="8" cy="9" r="1"/><circle cx="12" cy="7" r="1"/><circle cx="16" cy="9" r="1"/><path d="M16 15h2a2 2 0 0 1 0 4h-3"/>',timer:'<circle cx="12" cy="13" r="8"/><path d="M9 2h6M12 5v8l4 2"/>',users:'<circle cx="9" cy="9" r="3"/><path d="M3 19c.6-3.4 2.6-5 6-5s5.4 1.6 6 5M16 8a3 3 0 0 1 0 6M17 14c2.2.4 3.5 1.8 4 4"/>',shield:'<path d="M12 3 20 6v6c0 5-3 8-8 10-5-2-8-5-8-10V6z"/><path d="m9 12 2 2 4-5"/>',camera:'<rect x="3" y="6" width="18" height="14" rx="3"/><circle cx="12" cy="13" r="4"/><path d="m8 6 1-2h6l1 2"/>',qr:'<path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h2v2h-2zM18 14h2v6h-4v-2h-2"/>',spark:'<path d="m12 2 1.5 6.5L20 10l-6.5 1.5L12 18l-1.5-6.5L4 10l6.5-1.5z"/>',shop:'<path d="M4 9h16l-1 11H5zM8 9a4 4 0 0 1 8 0"/>',globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/>',check:'<path d="m5 12 4 4 10-10"/>',trash:'<path d="M5 7h14M9 7V4h6v3M7 7l1 14h8l1-14"/>',edit:'<path d="m4 20 4-1 11-11-3-3L5 16zM14 6l3 3"/>',pin:'<path d="m8 4 8 8M7 11l6 6M10 7l7-3 3 3-3 7M13 17l-5 4 4-5"/>',archive:'<path d="M4 7h16v13H4zM3 4h18v4H3zM9 12h6"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',music:'<path d="M9 18V6l9-2v12M9 18a3 3 0 1 1-3-3h3M18 16a3 3 0 1 1-3-3h3"/>',poll:'<path d="M5 20V10M12 20V4M19 20v-7"/>',link:'<path d="M10 13a5 5 0 0 0 7 0l2-2a5 5 0 0 0-7-7l-1 1M14 11a5 5 0 0 0-7 0l-2 2a5 5 0 0 0 7 7l1-1"/>'
};return `<svg class="ico" width="${size}" height="${size}" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.spark}</svg>`}
function seed(){
 const base=Date.now();
 const profiles={
  me:{id:'me',name:'Šimi',username:'@simi',bio:'Building LINK · solo PWA testing',verified:true,plan:'pro',presence:'online',statusText:'Building LINK PWA',statusEmoji:'⚡️',statusColor:'#6C5CE7',statusGradient:'cyber',photo:null,instagram:'@simi',spotify:'',website:'',coins:1650,effect:'halo',profileLayout:'default',isAdmin:false,role:'user'},
  link:{id:'link',name:'LINK Official',username:'@link',bio:'Official updates from LINK Production.',verified:true,official:true,isAdmin:true,role:'ceo',plan:'pro',presence:'online',statusText:'LINK 4.4 · ONE',statusEmoji:'✨',statusColor:'#E7B83B',effect:'admin_crown'},
  noa:{id:'noa',name:'Noa',username:'@noa',bio:'music · design · prague',verified:true,plan:'plus',presence:'online',statusText:'studio mode',statusEmoji:'🎧',statusColor:'#FF6482'},
  eli:{id:'eli',name:'Eli',username:'@eli.wav',bio:'creating things',verified:false,plan:'free',presence:'busy',statusText:'working',statusEmoji:'☕️',statusColor:'#FF9F0A'},
  max:{id:'max',name:'Max',username:'@maxx',bio:'night drives & live shows',verified:true,plan:'pro',presence:'online',statusText:'outside',statusEmoji:'🌙',statusColor:'#0A84FF',effect:'void'},
  sof:{id:'sof',name:'Sofie',username:'@sof',bio:'camera roll enthusiast',verified:false,plan:'free',presence:'offline',statusText:'offline',statusEmoji:'✨',statusColor:'#8E8E93'},
  dom:{id:'dom',name:'Dominik',username:'@dominik',bio:'LINK beta tester',verified:false,plan:'plus',presence:'dnd',statusText:'do not disturb',statusEmoji:'💀',statusColor:'#FF453A'},
 };
 const posts=[
  {id:'p1',author:'link',text:'LINK 4.4 ONE is live in the latest testing build. Feed, Discover, Posts 2.0 and messaging now share one social layer.',createdAt:base-8*60000,likes:['me','noa','max'],reposts:['eli'],bookmarks:['me'],pinned:true,media:'Everything. One LINK.',tag:'LINK44'},
  {id:'p2',author:'noa',text:'new mix tonight 🎧\n#studio #music',createdAt:base-34*60000,likes:['me','eli'],reposts:[],bookmarks:[],media:'late night sessions',tag:'music'},
  {id:'p3',author:'max',text:'This chat theme is too clean. Sky Blue forever.',createdAt:base-2.4*3600000,likes:['noa'],reposts:['me'],bookmarks:['me'],quoteOf:null},
  {id:'p4',author:'me',text:'Porting LINK 4.4 to PWA. Local-first now, backend later.',createdAt:base-4.3*3600000,likes:['noa','max'],reposts:[],bookmarks:[],media:'PWA · SOLO TEST',tag:'build'},
  {id:'p5',author:'eli',text:'Anyone going to the show next week?',createdAt:base-8*3600000,likes:['sof'],reposts:[],bookmarks:[]},
  {id:'p6',author:'dom',text:'LINK Notes >>>',createdAt:base-23*3600000,likes:['me','eli','sof'],reposts:[],bookmarks:[]},
 ];
 const messages={
  link:[{id:'m0',from:'link',text:'Welcome to LINK 4.4 · ONE. This PWA build runs locally without a backend.',at:base-30*60000,read:true}],
  noa:[{id:'m1',from:'noa',text:'yo, did you see the new profile effects?',at:base-55*60000,read:true},{id:'m2',from:'me',text:'yeah 😭 the new LINK Pro ones are crazy',at:base-52*60000,read:true},{id:'m3',from:'noa',text:'send me the PWA when it’s ready',at:base-49*60000,read:false}],
  max:[{id:'m4',from:'max',text:'Sky Blue theme still clears.',at:base-4*3600000,read:true},{id:'m5',from:'me',text:'Classic 😮‍💨',at:base-3.9*3600000,read:true}],
 };
 const groups={
  g1:{id:'g1',name:'LINK Testers',members:['me','noa','max','eli'],creator:'me',everyoneRename:false,inviteEnabled:true,inviteCode:'LNK443',announcementsOnly:false,slowMode:0,allowPolls:true,adminNote:'Keep testing the PWA build.',theme:'blue_purple',messages:[{id:'gm1',from:'max',text:'group chat works 👀',at:base-90*60000,read:true},{id:'gm2',from:'noa',text:'try double tap on this',at:base-86*60000,read:true},{id:'gm3',from:'me',text:'❤️',at:base-85*60000,read:true}],polls:[{id:'poll1',question:'Best chat theme?',options:['Sky Blue','Sunset','Monochromatic'],votes:{'me':0,'noa':1,'max':0}}]},
 };
 return {version:3,theme:'system',language:'en',tab:'feed',profileTab:'posts',meId:'me',profiles,connected:['noa','max','eli','dom'],requests:[{id:'r1',from:'sof'}],posts,moments:[{id:'mo1',owner:'me',caption:'LINK PWA',emoji:'⚡️',createdAt:base-13*60000,viewCount:4},{id:'mo2',owner:'noa',caption:'studio',emoji:'🎧',createdAt:base-21*60000,viewCount:18},{id:'mo3',owner:'max',caption:'night',emoji:'🌙',createdAt:base-71*60000,viewCount:24},{id:'mo4',owner:'eli',caption:'coffee',emoji:'☕️',createdAt:base-92*60000,viewCount:9}],notes:[{id:'n1',owner:'me',text:'PWA build ⚡️',createdAt:base-10*60000,audience:'all'},{id:'n2',owner:'noa',text:'new mix soon',createdAt:base-28*60000,audience:'all'},{id:'n3',owner:'max',text:'who’s out?',createdAt:base-41*60000,audience:'all'},{id:'n4',owner:'eli',text:'☕️ + code',createdAt:base-75*60000,audience:'all'}],linkNow:{me:{text:'Shipping LINK PWA',emoji:'⚡️'},noa:{text:'In studio',emoji:'🎧'},max:{text:'Out tonight',emoji:'🌙'}},messages,groups,notifications:[{id:'a1',type:'like',from:'noa',text:'liked your post',at:base-12*60000,read:false,postId:'p4'},{id:'a2',type:'reply',from:'max',text:'replied to your post',at:base-45*60000,read:false,postId:'p4'},{id:'a3',type:'link',from:'sof',text:'sent you a LINK request',at:base-2*3600000,read:false}],settings:{profileVisibility:'links',messagesFrom:'links',linkRequestsFrom:'everyone',showActivity:true,showLastActive:true,readReceipts:true,typing:true,profileViews:true,discoverUsername:true,discoverEmail:false,showStatus:true,showSocials:true,momentsToLinks:true,notifMessages:true,notifRequests:true,notifMoments:true,notifProduct:false,loginAlerts:true,doubleTap:'❤️'},chatThemes:{noa:'default',max:'sky_blue',g1:'blue_purple'},chatScopes:{},silentChats:{},favorites:['noa'],blocked:[],reports:[],accounts:['me'],ownedEffects:['halo'],highlights:[{id:'h1',name:'Builds',emoji:'⚡️'},{id:'h2',name:'LINK',emoji:'🔗'}],officialAnnouncements:[{id:'oa1',title:'LINK 4.4 · Reliability 443',body:'Messaging reliability, ONE social feed and the latest group-chat layer are included in the source build.',at:base-20*60000,read:false}],drafts:{},dev:{staffPreview:false},coins:1650};
}
function mergeSeed(saved){const d=seed();if(!saved||typeof saved!=='object')return d;return {...d,...saved,profiles:{...d.profiles,...saved.profiles},settings:{...d.settings,...saved.settings},messages:{...d.messages,...saved.messages},groups:{...d.groups,...saved.groups},chatThemes:{...d.chatThemes,...saved.chatThemes},dev:{...d.dev,...saved.dev}}}
function load(){try{return mergeSeed(JSON.parse(localStorage.getItem(STORE)||'null'))}catch{return seed()}}
let state=load(),overlay=null,currentChat=null,currentMoment=null,contextMsg=null,replyingTo=null,deferredInstall=null;
function save(){localStorage.setItem(STORE,JSON.stringify(state));applyTheme()}
function me(){return state.profiles[state.meId]||state.profiles.me}
function person(pid){return state.profiles[pid]||{id:pid,name:'Unknown',username:'@unknown',presence:'offline',plan:'free'}}
function isPlus(){return ['plus','pro'].includes(me().plan)||me().isAdmin||state.dev.staffPreview}
function isPro(){return me().plan==='pro'||me().isAdmin||state.dev.staffPreview}
function isStaff(){return me().isAdmin||state.dev.staffPreview}
function applyTheme(){let th=state.theme;if(th==='system')th=matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';document.documentElement.dataset.theme=th;const meta=qs('meta[name="theme-color"]');if(meta)meta.content=th==='dark'?'#090a0d':'#f7f7fa'}
function toast(msg){const h=qs('#toastHost');if(!h)return;h.innerHTML=`<div class="toast">${esc(msg)}</div>`;clearTimeout(toast._t);toast._t=setTimeout(()=>h.innerHTML='',2200)}
function verify(p){return p?.verified?`<span class="verify ${p.official?'gold':''}">✓</span>`:''}
function planBadge(p){if(p?.isAdmin||p?.official)return `<span class="plan-badge staff">${p.role==='ceo'?'LINK CEO':'STAFF'}</span>`;if(p?.plan==='pro')return '<span class="plan-badge pro">LINK PRO</span>';if(p?.plan==='plus')return '<span class="plan-badge plus">LINK PLUS</span>';return ''}
function avatar(p,size='md',presence=true){const status=p?.presence||'offline';return `<div class="avatar ${size}" ${p?.effect&&p.effect!=='none'?`style="box-shadow:0 0 0 2px var(--bg),0 0 24px ${PROFILE_EFFECTS.find(x=>x.id===p.effect)?.fx||'#6C5CE7'}66"`:''}><span>${esc(initials(p?.name))}</span>${presence&&status!=='ghost'?`<i class="presence ${status}"></i>`:''}</div>`}
function header(title='LINK',sub=BUILD,actions=''){return `<div class="topbar"><div><div class="brand">${esc(title)}</div>${sub?`<div class="build">${esc(sub)}</div>`:''}</div><div class="row gap8">${actions}</div></div>`}
function pillStatus(p){let style=`background:${p.statusColor||'#6C5CE7'}18;color:${p.statusColor||'#6C5CE7'}`;if(p.statusGradient){const g=STATUS_GRADIENTS.find(x=>x[0]===p.statusGradient)?.[1];if(g)style=`background:linear-gradient(135deg,${g.join(',')});color:#fff`;}return `<span class="status-pill" style="${style}"><b>${esc(p.statusEmoji||'✨')}</b>${esc(p.statusText||'Online')}</span>`}
function nav(){const unread=countUnreadChats(),activity=state.notifications.filter(x=>!x.read).length+state.requests.length;const items=[['feed','feed','Feed'],['discover','discover','Discover'],['create','plus','Create'],['chats','chats','Chats'],['profile','profile','Profile']];return `<div class="nav-shell"><div class="nav">${items.map(([key,ic,label])=>`<button class="navbtn ${state.tab===key?'active':''} ${key==='create'?'create':''}" data-tab="${key}">${key==='create'?`<span class="create-orb">${icon('plus',25)}</span>`:`${icon(ic,21)}<span>${t(label)}</span>`}${key==='chats'&&unread?`<b class="nav-badge">${unread>99?'99+':unread}</b>`:''}${key==='discover'&&activity?`<b class="nav-badge">${activity>99?'99+':activity}</b>`:''}</button>`).join('')}</div></div>`}
function countUnreadChats(){let n=state.officialAnnouncements.filter(x=>!x.read).length;Object.values(state.messages).forEach(a=>n+=a.filter(m=>m.from!==state.meId&&!m.read).length);Object.values(state.groups).forEach(g=>n+=(g.messages||[]).filter(m=>m.from!==state.meId&&!m.read).length);return n}
function app(){applyTheme();const root=qs('#app');root.innerHTML=`<main class="app-shell">${screen()}${!currentChat?nav():''}${currentChat?chatPage():''}${currentMoment?momentView():''}${overlay?renderOverlay():''}${contextMsg?messageContext():''}</main>`;bind();}
function screen(){if(state.tab==='discover')return discoverScreen();if(state.tab==='chats')return chatsScreen();if(state.tab==='profile')return profileScreen();return feedScreen()}
function feedScreen(){const unread=state.notifications.filter(x=>!x.read).length;return `<section class="screen">${header('LINK','ONE · Full Solo 443',`<button class="iconbtn" data-open="search">${icon('search')}</button><button class="iconbtn" data-open="activity">${icon('bell')}${unread?`<span style="position:absolute"></span>`:''}</button>`)}
 <div class="hero"><div class="hero-eyebrow">LINK 4.4 · ONE</div><h1>Everything. One LINK.</h1><p>Posts, Moments, Notes, live identity and conversations in one local-first PWA.</p><div class="hero-actions"><button class="hero-pill" data-open="whatsnew">What’s new</button><button class="hero-pill" data-open="pulse">LINK Pulse</button><button class="hero-pill" data-open="mylink">Show my LINK</button></div></div>
 ${pulseStrip()}
 <div class="sectionhead"><h2>Notes</h2><button data-open="note">Write a note</button></div>${notesRow()}
 <div class="sectionhead"><h2>Moments</h2><button data-open="moment">New Moment</button></div>${momentsRow()}
 ${backstageCard()}${officialCard()}
 <div class="sectionhead"><h2>Feed</h2><button data-open="post">Create post</button></div>${feedPosts(state.posts)}
 </section>`}
function pulseStrip(){const arr=Object.entries(state.linkNow).filter(([pid])=>state.profiles[pid]);return `<div class="pulse-strip">${arr.map(([pid,s])=>`<button class="pulse" data-profile="${pid}"><span class="dot"></span><b>${esc(person(pid).name)}</b><span>${esc(s.emoji||'✨')} ${esc(s.text)}</span></button>`).join('')}</div>`}
function notesRow(){const mine=state.notes.find(n=>n.owner===state.meId);const arr=[{mine:true,owner:state.meId,text:mine?.text||'Add Note'},...state.notes.filter(n=>n.owner!==state.meId).slice(0,7)];return `<div class="hscroll">${arr.map(n=>{const p=person(n.owner);return `<button class="note-item" style="border:0;background:none;color:inherit;padding:0" ${n.mine?'data-open="note"':`data-note="${state.notes.find(x=>x.owner===n.owner)?.id||''}"`}><div class="note-bubble">${esc(n.text)}</div>${avatar(p,'sm')}<div class="note-name">${n.mine?'Your Note':esc(p.name)}</div></button>`}).join('')}</div>`}
function momentsRow(){const mine=state.moments.find(x=>x.owner===state.meId);const arr=[{id:'new',owner:state.meId,caption:mine?.caption||'Your Moment',mine:true},...state.moments.filter(x=>x.owner!==state.meId).slice(0,8)];return `<div class="hscroll">${arr.map(m=>{const p=person(m.owner);return `<button class="moment-item" style="border:0;background:none;color:inherit;padding:0" ${m.mine?'data-open="moment"':`data-moment="${m.id}"`}><div class="avatar-ring">${avatar(p,'md',false)}</div><div class="moment-name">${m.mine?'Your Moment':esc(p.name)}</div></button>`}).join('')}</div>`}
function backstageCard(){return `<button class="card backstage" data-open="backstage" style="width:100%;text-align:left"><div class="row gap10"><div class="backstage-mark">B</div><div class="grow"><b>BACKSTAGE</b><div class="sub">Artists, releases and events · install guide included</div></div><span>›</span></div></button>`}
function officialCard(){const a=state.officialAnnouncements[0];if(!a)return'';return `<button class="card official-card" data-chat="link" style="width:100%;text-align:left"><div class="row gap10"><div class="official-mark">L</div><div class="grow"><div class="row gap4"><b>${esc(a.title)}</b>${verify(person('link'))}</div><div class="sub">${esc(a.body)}</div></div>${!a.read?'<span class="pill" style="background:#ffd45d;color:#211600;border:0">NEW</span>':''}</div></button>`}
function feedPosts(posts){return `<div>${posts.filter(p=>!p.deleted).sort((a,b)=>(b.pinned?1:0)-(a.pinned?1:0)||b.createdAt-a.createdAt).map(postCard).join('')}</div>`}
function postCard(p){const a=person(p.author),liked=(p.likes||[]).includes(state.meId),saved=(p.bookmarks||[]).includes(state.meId),reposted=(p.reposts||[]).includes(state.meId);return `<article class="card post" data-post="${p.id}"><div class="post-head"><button style="border:0;background:none;padding:0" data-profile="${a.id}">${avatar(a,'sm')}</button><div class="grow"><div class="row gap4"><span class="post-name">${esc(a.name)}</span>${verify(a)}${planBadge(a)}</div><div class="post-user">${esc(a.username)} · ${ago(p.createdAt)}${p.pinned?' · Pinned':''}</div></div><button class="post-action" data-post-menu="${p.id}">${icon('dots',19)}</button></div>${p.repostBy?`<div class="post-user" style="margin-top:8px">↻ Reposted by ${esc(person(p.repostBy).name)}</div>`:''}<div class="post-text">${esc(p.text)}</div>${p.quoteOf?quoteCard(p.quoteOf):''}${p.media?`<div class="post-media">${esc(p.media)}</div>`:''}<div class="post-actions"><button class="post-action ${liked?'active':''}" data-like="${p.id}">${icon('heart',18)}<span>${(p.likes||[]).length}</span></button><button class="post-action" data-reply-post="${p.id}">${icon('comment',18)}<span>${state.posts.filter(x=>x.replyTo===p.id&&!x.deleted).length}</span></button><button class="post-action ${reposted?'active':''}" data-repost="${p.id}">${icon('repeat',18)}<span>${(p.reposts||[]).length}</span></button><button class="post-action ${saved?'active':''}" data-bookmark="${p.id}">${icon('bookmark',18)}</button></div></article>`}
function quoteCard(id){const p=state.posts.find(x=>x.id===id);if(!p)return'';return `<div class="post-quote"><div class="post-name">${esc(person(p.author).name)} ${verify(person(p.author))}</div><div class="post-user">${esc(person(p.author).username)}</div><div style="font-size:11px;margin-top:6px">${esc(p.text)}</div></div>`}
function discoverScreen(){const activity=state.notifications.filter(x=>!x.read).length;return `<section class="screen">${header(t('Discover'),'People, posts & #topics',`<button class="iconbtn" data-open="search">${icon('search')}</button><button class="iconbtn" data-open="activity">${icon('bell')}</button>`)}<div class="searchbar">${icon('search',18)}<input id="discoverSearch" placeholder="Search people, posts or #topics" /></div>${requestsBlock()}<div class="sectionhead"><h2>${t('Trending now')}</h2></div><div class="trends">${['#LINK44','#PWA','#music','#Prague','#design','#ios'].map(x=>`<button class="trend" data-trend="${x}">${x}</button>`).join('')}</div><div class="sectionhead"><h2>${t('People you may know')}</h2></div><div class="card" id="peopleResults">${peopleList(Object.values(state.profiles).filter(p=>!state.connected.includes(p.id)&&p.id!==state.meId&&p.id!=='link'))}</div><div class="sectionhead"><h2>Discover posts</h2></div><div id="discoverPosts">${feedPosts(state.posts.filter(p=>p.author!==state.meId).slice().sort((a,b)=>(b.likes?.length||0)-(a.likes?.length||0)))}</div></section>`}
function requestsBlock(){if(!state.requests.length)return'';return `<div class="sectionhead"><h2>${t('Incoming requests')}</h2><span class="pill accent">${state.requests.length}</span></div><div class="card requests">${state.requests.map(r=>{const p=person(r.from);return `<div class="request">${avatar(p,'sm')}<div class="grow"><b>${esc(p.name)}${verify(p)}</b><div class="sub">${esc(p.username)}</div></div><div class="request-actions"><button class="mini primary" data-accept="${r.id}">Accept</button><button class="mini" data-decline="${r.id}">Decline</button></div></div>`}).join('')}</div>`}
function peopleList(arr){return arr.map(p=>`<button class="person" data-profile="${p.id}" style="width:100%;border:0;background:none;color:inherit;text-align:left">${avatar(p,'sm')}<div class="grow"><h3>${esc(p.name)}${verify(p)} ${planBadge(p)}</h3><div class="sub">${esc(p.username)} · ${esc(p.statusEmoji||'✨')} ${esc(p.statusText||'')}</div></div>${state.connected.includes(p.id)?'<span class="pill green">LINKED</span>':'<span class="pill">View</span>'}</button>`).join('')||'<div class="empty"><strong>No people</strong>Nothing to show here.</div>'}
function chatsScreen(){const rows=[{type:'official',id:'link',name:'LINK Official'},...Object.keys(state.messages).filter(x=>x!=='link').map(id=>({type:'dm',id})),...Object.values(state.groups).map(g=>({type:'group',id:g.id}))];return `<section class="screen">${header(t('Chats'),t('Direct + group chats · local solo mode.'),`<button class="iconbtn" data-open="search">${icon('search')}</button><button class="iconbtn" data-open="newgroup">${icon('users')}</button>`)}<div class="row gap8" style="margin:10px 0 13px"><button class="pill accent" data-chat-filter="inbox">Inbox</button><button class="pill" data-chat-filter="archived">Archived</button></div><div id="chatList">${rows.map(chatRow).join('')}</div></section>`}
function chatRow(r){if(r.type==='group'){const g=state.groups[r.id],last=(g.messages||[]).at(-1),unread=(g.messages||[]).filter(m=>m.from!==state.meId&&!m.read).length;return `<button class="chatrow" data-chat="${g.id}" style="width:100%;border:0;background:none;color:inherit;text-align:left"><div class="avatar sm"><span>👥</span></div><div class="grow"><h3>${esc(g.name)}</h3><div class="sub">${last?`${esc(person(last.from).name)}: ${esc(last.text)}`:`${g.members.length} members`}</div></div><div style="text-align:right"><div class="sub">${last?ago(last.at):''}</div>${unread?`<span class="pill accent">${unread}</span>`:''}</div></button>`}
 const p=person(r.id),list=state.messages[r.id]||[],last=list.at(-1),unread=list.filter(m=>m.from!==state.meId&&!m.read).length;return `<button class="chatrow" data-chat="${p.id}" style="width:100%;border:0;background:none;color:inherit;text-align:left">${p.id==='link'?'<div class="official-mark" style="width:38px;height:38px;border-radius:50%">L</div>':avatar(p,'sm')}<div class="grow"><h3>${esc(p.name)}${verify(p)} ${planBadge(p)}</h3><div class="sub">${last?esc(last.text):esc(p.username)}</div></div><div style="text-align:right"><div class="sub">${last?ago(last.at):''}</div>${unread?`<span class="pill accent">${unread}</span>`:''}</div></button>`}
function profileScreen(){const p=me(),posts=state.posts.filter(x=>x.author===p.id&&!x.deleted),likes=state.posts.filter(x=>(x.likes||[]).includes(p.id)&&!x.deleted);let list=posts;if(state.profileTab==='replies')list=state.posts.filter(x=>x.author===p.id&&x.replyTo&&!x.deleted);if(state.profileTab==='likes')list=likes;if(state.profileTab==='media')list=posts.filter(x=>x.media);return `<section class="screen">${header(t('Profile'),t('Your profile'),`<button class="iconbtn" data-open="search">${icon('search')}</button><button class="iconbtn" data-open="settings">${icon('gear')}</button>`)}<div class="card profilehero">${avatar(p,'lg')}<div class="displayname">${esc(p.name)}${verify(p)}</div><div class="username">${esc(p.username)}</div><div class="badges">${planBadge(p)}${isStaff()?'<span class="plan-badge staff">STAFF PREVIEW</span>':''}</div><div class="bio">${esc(p.bio||'')}</div><div style="margin-top:10px">${pillStatus(p)}</div><div class="stats"><div class="stat"><strong>${state.connected.length}</strong><span>LINKs</span></div><div class="stat"><strong>${posts.length}</strong><span>Posts</span></div><div class="stat"><strong>${state.highlights.length}</strong><span>Highlights</span></div><div class="stat"><strong>${p.coins||state.coins}</strong><span>Coins</span></div></div></div><div class="profile-actions"><button class="btn secondary grow" data-open="editprofile">Edit profile</button><button class="btn secondary grow" data-open="mylink">Show my LINK</button><button class="btn secondary" data-open="pulse">Pulse</button></div><div class="sectionhead"><h2>Highlights</h2><button data-open="moment">Add</button></div><div class="highlight-row">${state.highlights.map(h=>`<button class="highlight" style="border:0;background:none;color:inherit"><div class="highlight-circle">${esc(h.emoji)}</div><div class="highlight-name">${esc(h.name)}</div></button>`).join('')}</div><div class="sectionhead"><h2>Profile</h2></div><div class="profile-tabs">${[['posts','Posts'],['replies','Replies'],['media','Media'],['likes','Likes']].map(([k,l])=>`<button class="profile-tab ${state.profileTab===k?'active':''}" data-profile-tab="${k}">${l}</button>`).join('')}</div><div style="margin-top:11px">${feedPosts(list)}</div></section>`}
function chatPage(){const g=state.groups[currentChat],p=g?null:person(currentChat),list=g?(g.messages||[]):(state.messages[currentChat]||[]),themeId=state.chatThemes[currentChat]||'default',th=CHAT_THEMES.find(x=>x.id===themeId)||CHAT_THEMES[0],silent=state.silentChats[currentChat],pinned=list.find(x=>x.pinned&&!x.deleted);if(currentChat==='link')state.officialAnnouncements.forEach(a=>a.read=true);list.forEach(m=>{if(m.from!==state.meId)m.read=true});save();return `<section class="chatpage" style="--bubble-a:${th.a};--bubble-b:${th.b};--bubble-text:${th.text}"><div class="chathead"><button class="back" data-chat-close>${icon('back')}</button>${g?'<div class="avatar sm"><span>👥</span></div>':(p.id==='link'?'<div class="official-mark" style="width:38px;height:38px;border-radius:50%">L</div>':avatar(p,'sm'))}<button class="grow" style="border:0;background:none;text-align:left;color:inherit" ${g?`data-group-settings="${g.id}"`:`data-profile="${p.id}"`}><strong>${esc(g?g.name:p.name)}${!g?verify(p):''}</strong><div class="sub">${g?`${g.members.length} members${g.announcementsOnly?' · Announcements only':''}`:p.id==='link'?'Official channel · read only':`${p.presence==='online'?'Active now':'Local solo chat'}${silent?' · Silent Chat':''}`}</div></button><div class="chat-tools"><button class="chat-tool" data-open-chat-theme>${icon('palette',18)}</button><button class="chat-tool" data-open-chat-info>${icon('info',18)}</button></div></div>${pinned?`<button class="pinned" data-msg-context="${pinned.id}" style="border:0;width:100%;text-align:left">📌 ${esc(pinned.text)}</button>`:''}<div class="chatbody" id="chatBody"><div class="date-pill">Today · Local Solo</div>${g&&g.polls?.length?g.polls.map(x=>pollCard(g,x)).join(''):''}${list.filter(x=>!x.deletedForMe).map(m=>messageBubble(m,g)).join('')}</div>${currentChat==='link'?`<div class="composer"><div class="grow center muted" style="font-size:11px;padding:10px">LINK Official is read-only.</div></div>`:`${replyingTo?`<div class="typing">Replying to ${esc(person(replyingTo.from).name)} · ${esc(replyingTo.text.slice(0,70))} <button data-cancel-reply style="border:0;background:none;color:var(--accent);font-weight:850">×</button></div>`:''}<div class="composer"><button class="chat-tool" data-chat-plus>${icon('plus',18)}</button><textarea id="composer" rows="1" placeholder="Message">${esc(state.drafts[currentChat]||'')}</textarea><button class="send" data-send>${icon('send',19)}</button></div>`}</section>`}
function messageBubble(m,g){const mine=m.from===state.meId,a=person(m.from),showSender=g&&!mine;return `<div class="msgrow ${mine?'me':'them'}" data-msg="${m.id}"><div class="msgwrap">${showSender?`<div class="sender-name">${esc(a.name)}</div>`:''}<div class="bubble" data-msg-context="${m.id}" data-dbl-msg="${m.id}">${m.replyTo?replyPreview(m.replyTo,g):''}${m.deletedEveryone?'Message deleted':esc(m.text)}${m.edited?'<span style="opacity:.55;font-size:9px"> · Edited</span>':''}<div class="msgmeta">${fmtTime(m.at)}${mine?' · '+(m.read?'Seen':'Sent'):''}</div></div>${m.reaction?`<span class="reaction">${esc(m.reaction)}</span>`:''}</div></div>`}
function replyPreview(id,g){const list=g?(g.messages||[]):(state.messages[currentChat]||[]),m=list.find(x=>x.id===id);return m?`<div class="replybox">${esc(person(m.from).name)} · ${esc(m.text.slice(0,60))}</div>`:''}
function pollCard(g,p){const total=Object.keys(p.votes||{}).length;return `<div class="poll"><div class="poll-title">📊 ${esc(p.question)}</div>${p.options.map((o,i)=>{const n=Object.values(p.votes||{}).filter(v=>v===i).length,pct=total?Math.round(n/total*100):0,sel=p.votes?.[state.meId]===i;return `<button class="poll-opt" data-vote="${p.id}:${i}" style="width:100%;background:${sel?'rgba(108,92,231,.08)':'transparent'}"><i class="poll-fill" style="width:${pct}%"></i><span>${esc(o)}</span><span>${pct}%</span></button>`}).join('')}</div>`}
function momentView(){const m=state.moments.find(x=>x.id===currentMoment);if(!m){currentMoment=null;return''}const p=person(m.owner);return `<section class="fullpage moment-view"><div class="moment-head">${avatar(p,'sm',false)}<div class="grow"><b>${esc(p.name)}${verify(p)}</b><div style="font-size:10px;opacity:.6">Moment · ${ago(m.createdAt)} · ${m.viewCount||0} views</div></div><button class="close" data-close-moment style="background:rgba(255,255,255,.1);color:#fff;border-color:rgba(255,255,255,.15)">×</button></div><div class="moment-stage"><div><div style="font-size:76px">${esc(m.emoji||'✨')}</div><div class="caption">${esc(m.caption||'Moment')}</div></div></div><div class="moment-actions">${['❤️','🔥','😂','😍','👏'].map(e=>`<button data-moment-react="${e}">${e}</button>`).join('')}<button class="grow" data-moment-reply>Reply</button>${m.owner===state.meId?'<button data-highlight-moment>Highlight</button>':'<button data-repost-moment>↻</button>'}</div></section>`}
function renderOverlay(){const fn={search:searchModal,activity:activityModal,whatsnew:whatsNewModal,pulse:pulseModal,mylink:myLinkModal,note:noteModal,moment:momentComposer,post:postComposer,backstage:backstageModal,settings:settingsModal,editprofile:editProfileModal,newgroup:newGroupModal,profile:personModal,chatTheme:chatThemeModal,chatInfo:chatInfoModal,groupSettings:groupSettingsModal,messagePlus:messagePlusModal,plus:plusModal,pro:proModal,shop:shopModal,status:statusModal,doubleTap:doubleTapModal,safety:safetyModal,accounts:accountsModal,staff:staffModal,thread:threadModal,postMenu:postMenuModal,noteView:noteViewModal,report:reportModal,qrscan:scanModal,install:installModal};return fn[overlay?.type]?.()||''}
function modalShell(title,body,opts={}){return `<div class="modalback" data-backdrop><div class="sheet ${opts.full?'full':''}"><div class="grab"></div><div class="sheethead"><h2>${esc(title)}</h2><button class="close" data-close-overlay>×</button></div>${opts.sub?`<div class="sheet-sub">${opts.sub}</div>`:''}${body}</div></div>`}
function fullShell(title,body){return `<section class="fullpage"><div class="fullhead"><button class="back" data-close-overlay>${icon('back')}</button><b class="grow">${esc(title)}</b></div><div class="fullbody">${body}</div></section>`}
function searchModal(){return modalShell('Search',`<div class="searchbar">${icon('search',18)}<input id="globalSearch" placeholder="People, posts, groups, chats" autofocus /></div><div id="searchResults"></div>`,{full:true,sub:'Unified Search · LINK 4.4 style'})}
function activityModal(){return fullShell(t('Activity'),`<div class="row-between" style="margin-bottom:10px"><span class="muted" style="font-size:11px">Likes, replies, LINK requests and official updates.</span><button class="mini" data-read-all>Mark all read</button></div><div class="card">${state.notifications.map(n=>{const p=person(n.from);return `<button class="person" data-activity="${n.id}" style="width:100%;border:0;background:${n.read?'none':'rgba(108,92,231,.045)'};color:inherit;text-align:left">${avatar(p,'sm')}<div class="grow"><h3>${esc(p.name)}${verify(p)}</h3><div class="sub">${esc(n.text)} · ${ago(n.at)}</div></div>${!n.read?'<span class="pill accent">NEW</span>':''}</button>`}).join('')||'<div class="empty"><strong>All caught up</strong>No new activity.</div>'}</div>`)}
function whatsNewModal(){const rows=[['Feed 4.0','Following and Discover posts now live in one social timeline.'],['Posts 2.0','Replies, threads, reposts, quote posts, bookmarks, likes and pinned posts.'],['Discover','Find people, posts and trending hashtags.'],['Profile 4.0','Posts, Replies, Media and Likes live directly on every LINK profile.'],['Create Hub','Create a Post, Moment, Note, Group or LINK Now from one place.'],['LINK Pulse','Live statuses from your LINKs appear directly in Feed.'],['Activity 4.0','Post likes, replies, quotes and reposts appear in Activity.'],['Messaging reliability','Local inbox watchdog is replaced by direct local persistence in this solo PWA.'],['Group v3.5','Roles, invite codes, admin note, slow mode, announcements and polls.'],['LINK Official','Official updates live in the same ONE feed.']];return fullShell('What’s new',`<div class="hero"><div class="hero-eyebrow">LINK 4.4 / 443</div><h1>Everything. One LINK.</h1><p>This PWA ports the latest build’s major UI and local-testable product layers.</p></div><div class="card" style="padding:5px 13px">${rows.map(([a,b])=>`<div class="setting"><div class="seticon">${icon('spark',17)}</div><div class="grow"><strong>${esc(a)}</strong><small>${esc(b)}</small></div></div>`).join('')}</div>`)}
function pulseModal(){return modalShell('LINK Pulse',`<div class="sheet-sub">Live identity, Circles and LINK Now.</div><div class="settings-section"><div class="settings-title">Your LINK Now</div><div class="card status-preview">${pillStatus(me())}<div class="form-label">Text</div><input class="input" id="pulseText" value="${esc(state.linkNow[state.meId]?.text||'')}" maxlength="50"/><div class="form-label">Emoji</div><input class="input" id="pulseEmoji" value="${esc(state.linkNow[state.meId]?.emoji||'⚡️')}" maxlength="5"/><button class="btn primary wide" data-save-pulse style="margin-top:10px">Save LINK Now</button></div></div><div class="settings-section"><div class="settings-title">Your LINKs</div><div class="card">${state.connected.map(pid=>{const p=person(pid),s=state.linkNow[pid];return `<div class="setting">${avatar(p,'sm')}<div class="grow"><strong>${esc(p.name)}</strong><small>${s?`${esc(s.emoji)} ${esc(s.text)}`:'No LINK Now'}</small></div></div>`}).join('')}</div></div><div class="settings-section"><div class="settings-title">Circles · Pro preview</div><div class="card" style="padding:13px"><span class="pill">Close LINKs · ${Math.min(3,state.connected.length)}</span> <span class="pill">Testers · ${state.connected.length}</span></div></div>`)}
function fakeQR(text){let seedv=0;for(const c of text)seedv=(seedv*31+c.charCodeAt(0))>>>0;let x=seedv||123456;const cells=[];for(let i=0;i<289;i++){x=(x*1664525+1013904223)>>>0;let on=(x&3)!==0;const r=Math.floor(i/17),c=i%17;const finder=(r<5&&c<5)||(r<5&&c>11)||(r>11&&c<5);if(finder)on=(r===0||r===4||c===0||c===4||(r>=2&&r<=2&&c>=2&&c<=2));cells.push(`<i class="${on?'on':''}"></i>`)}return cells.join('')}
function myLinkModal(){const p=me(),payload=`LINK:${p.username}:${p.id}`;return modalShell('My LINK',`<div class="qr-card"><div class="link-card"><div class="row gap10">${avatar(p,'md',false)}<div><b style="font-size:18px">${esc(p.name)}${verify(p)}</b><div style="opacity:.6;font-size:12px">${esc(p.username)}</div></div></div><div style="margin-top:13px;font-size:11px;opacity:.68">tap · scan · connect</div></div><div class="qr">${fakeQR(payload)}</div><div class="muted" style="font-size:11px">Visual LINK card for solo testing. No backend identity lookup.</div><div class="row gap8" style="margin-top:13px"><button class="btn secondary grow" data-open="qrscan">Scan LINK</button><button class="btn primary grow" data-share-link>Share my LINK</button></div></div>`)}
function noteModal(){const n=state.notes.find(x=>x.owner===state.meId);return modalShell(n?'Edit Note':'New Note',`<div class="form-label">Note</div><textarea class="textarea" id="noteText" maxlength="80" placeholder="Leave a note…">${esc(n?.text||'')}</textarea><div class="form-label">Who can see it?</div><select class="select" id="noteAudience"><option value="all" ${n?.audience!=='close'?'selected':''}>All LINKs</option><option value="close" ${n?.audience==='close'?'selected':''}>Close LINKs</option></select><div class="row gap8" style="margin-top:12px">${n?'<button class="btn danger grow" data-delete-note>Delete Note</button>':''}<button class="btn primary grow" data-save-note>Save Note</button></div>`)}
function noteViewModal(){const n=state.notes.find(x=>x.id===overlay.id);if(!n)return'';const p=person(n.owner);return modalShell('Note',`<div class="center" style="padding:15px">${avatar(p,'lg')}<div class="displayname">${esc(p.name)}${verify(p)}</div><div class="note-bubble" style="height:auto;min-height:70px;margin:15px auto;max-width:280px;font-size:14px">${esc(n.text)}</div><button class="btn primary wide" data-note-reply="${n.id}">Reply privately to their Note</button></div>`)}
function momentComposer(){return modalShell('New Moment',`<div class="sheet-sub">Visible to your LINKs for 24 hours · local preview.</div><div class="form-label">Caption</div><textarea class="textarea" id="momentCaption" placeholder="Add a caption…"></textarea><div class="form-label">Moment emoji</div><input class="input" id="momentEmoji" value="✨" maxlength="5"/><div class="form-label">Audience</div><select class="select" id="momentAudience"><option value="all">All LINKs</option><option value="close">Close LINKs</option><option value="circle">Circle</option></select><div class="form-label">Music sticker</div><input class="input" id="momentMusic" placeholder="Track · Artist (optional)"/><button class="btn primary wide" data-save-moment style="margin-top:12px">Post Moment</button>`)}
function postComposer(){const reply=overlay.replyTo?state.posts.find(x=>x.id===overlay.replyTo):null,quote=overlay.quoteOf?state.posts.find(x=>x.id===overlay.quoteOf):null;return modalShell(reply?'Reply':quote?'Quote post':'Create post',`${reply?`<div class="post-quote"><b>Replying to ${esc(person(reply.author).name)}</b><div style="font-size:11px;margin-top:5px">${esc(reply.text)}</div></div>`:''}${quote?quoteCard(quote.id):''}<textarea class="textarea" id="postText" placeholder="What’s happening on LINK?" style="min-height:135px"></textarea><div class="form-label">Media card text (optional)</div><input class="input" id="postMedia" placeholder="Creates a visual media card"/><button class="btn primary wide" data-save-post style="margin-top:12px">Post</button>`)}
function backstageModal(){return fullShell('BACKSTAGE',`<div class="card backstage" style="padding:22px"><div class="backstage-mark">B</div><h2 style="font-size:30px;margin:16px 0 6px">LINK BACKSTAGE</h2><p style="font-size:13px;opacity:.68;line-height:1.45">Artist pages, releases and event discovery connected to the LINK ecosystem.</p></div><div class="sectionhead"><h2>Add to Home Screen</h2></div><div class="card" style="padding:14px"><div class="setting"><div class="seticon">1</div><div><strong>Open in Safari</strong><small>Use Safari on iPhone or iPad.</small></div></div><div class="setting"><div class="seticon">2</div><div><strong>Tap Share</strong><small>Open the iOS share sheet.</small></div></div><div class="setting"><div class="seticon">3</div><div><strong>Add to Home Screen</strong><small>Launch it later like a standalone app.</small></div></div></div>`)}
function editProfileModal(){const p=me();return fullShell(t('Edit profile'),`<div class="card" style="padding:14px"><div class="center">${avatar(p,'lg')}<button class="mini" style="margin-top:8px" data-random-photo>Change local avatar</button></div><div class="form-label">Display name</div><input class="input" id="editName" value="${esc(p.name)}"/><div class="form-label">Username</div><input class="input" id="editUser" value="${esc(p.username)}"/><div class="form-label">Short bio</div><textarea class="textarea" id="editBio">${esc(p.bio||'')}</textarea><div class="form-label">Instagram @handle</div><input class="input" id="editInstagram" value="${esc(p.instagram||'')}"/><div class="form-label">Spotify name</div><input class="input" id="editSpotify" value="${esc(p.spotify||'')}"/><div class="form-label">Website</div><input class="input" id="editWebsite" value="${esc(p.website||'')}"/><button class="btn primary wide" data-save-profile style="margin-top:12px">Save</button></div>`)}
function newGroupModal(){const list=state.connected.map(pid=>person(pid));return fullShell(t('New group'),`<div class="sheet-sub">Create a local group chat with your LINKs.</div><div class="form-label">Group name</div><input class="input" id="groupName" placeholder="Group name (optional)"/><div class="form-label">Add people</div><div class="card" id="groupMemberList">${list.map(p=>`<button class="person" data-member="${p.id}" style="width:100%;border:0;background:none;color:inherit;text-align:left">${avatar(p,'sm')}<div class="grow"><h3>${esc(p.name)}</h3><div class="sub">${esc(p.username)}</div></div><span class="pill">Add</span></button>`).join('')}</div><button class="btn primary wide" data-create-group style="margin-top:12px">Create Group Chat</button>`)}
function personModal(){const p=person(overlay.id),connected=state.connected.includes(p.id),blocked=state.blocked.includes(p.id),posts=state.posts.filter(x=>x.author===p.id&&!x.deleted);return fullShell('Profile',`<div class="card profilehero">${avatar(p,'lg')}<div class="displayname">${esc(p.name)}${verify(p)}</div><div class="username">${esc(p.username)}</div><div class="badges">${planBadge(p)}${state.favorites.includes(p.id)?'<span class="pill">★ Favorite</span>':''}</div><div class="bio">${esc(p.bio||'')}</div>${p.statusText?`<div style="margin-top:10px">${pillStatus(p)}</div>`:''}<div class="stats"><div class="stat"><strong>${posts.length}</strong><span>Posts</span></div><div class="stat"><strong>${connected?'1':'—'}</strong><span>Linked</span></div><div class="stat"><strong>${p.plan==='pro'?'PRO':p.plan==='plus'?'PLUS':'FREE'}</strong><span>Plan</span></div><div class="stat"><strong>${p.presence==='online'?'●':'○'}</strong><span>Status</span></div></div></div><div class="profile-actions">${p.id!==state.meId&&p.id!=='link'?`<button class="btn primary grow" data-open-person-chat="${p.id}">Message</button>${connected?`<button class="btn secondary grow" data-unlink="${p.id}">LINKED</button>`:`<button class="btn secondary grow" data-link-request="${p.id}">Send LINK request</button>`}<button class="btn secondary" data-favorite="${p.id}">${state.favorites.includes(p.id)?'★':'☆'}</button>`:''}</div>${p.id!=='link'&&p.id!==state.meId?`<div class="row gap8" style="margin-bottom:12px"><button class="btn secondary grow" data-block="${p.id}">${blocked?'Unblock':'Block'}</button><button class="btn secondary grow" data-report="${p.id}">Report</button></div>`:''}<div class="sectionhead"><h2>Posts</h2></div>${feedPosts(posts)}`)}
function chatThemeModal(){const cur=state.chatThemes[currentChat]||'default';return modalShell('Chat theme',`<div class="sheet-sub">Apply to message bubbles in this local conversation.</div>${['free','plus','pro'].map(tier=>`<div class="settings-section"><div class="settings-title">${tier==='free'?'Free':tier==='plus'?'LINK Plus':'LINK Pro'}</div><div class="theme-grid">${CHAT_THEMES.filter(x=>x.tier===tier).map(x=>{const allowed=tier==='free'||tier==='plus'&&isPlus()||tier==='pro'&&isPro();return `<button class="emoji-choice ${cur===x.id?'active':''}" data-chat-theme="${x.id}" ${allowed?'':'data-locked-theme="1"'} style="background:linear-gradient(135deg,${x.a},${x.b});color:${x.text};opacity:${allowed?1:.38}" title="${esc(x.name)}">${cur===x.id?'✓':''}</button>`}).join('')}</div></div>`).join('')}<div class="muted" style="font-size:10.5px">Free: Default, Red · Plus: 5 extra themes · Pro: premium gradients and classic Sky Blue.</div>`)}
function chatInfoModal(){const g=state.groups[currentChat],silent=state.silentChats[currentChat];return modalShell(g?'Group controls':'Chat controls',`<div class="settings-section"><div class="settings-title">Conversation</div><div class="card settings-list">${g?settingRow('Group settings','Members, roles and invite','users','groupSettings'):''}${settingRow('Chat theme',CHAT_THEMES.find(x=>x.id===(state.chatThemes[currentChat]||'default'))?.name,'palette','chatTheme')}${settingRow('Silent Chat',silent?`${silent}s timer`:'Off','timer','silent')}${settingRow('Encryption info','Solo build security model','lock','encryption')}${settingRow('Mark unread','Keep this chat highlighted','bell','markUnread')}${settingRow('Archive','Move from Inbox preview','archive','archiveChat')}</div></div><div class="settings-section"><div class="settings-title">Safety</div><div class="card settings-list">${settingRow('Safety Center','Block, report and devices','shield','safety')}</div></div>`)}
function settingRow(title,sub,ic,action){return `<button class="setting" data-setting-action="${action}" style="width:100%;border:0;background:none;color:inherit;text-align:left"><div class="seticon">${icon(ic,17)}</div><div class="grow"><strong>${esc(title)}</strong><small>${esc(sub||'')}</small></div><span class="chev">›</span></button>`}
function groupSettingsModal(){const g=state.groups[currentChat];if(!g)return'';return fullShell('Group settings',`<div class="card" style="padding:14px"><div class="center"><div class="avatar lg" style="margin:auto"><span>👥</span></div><div class="displayname">${esc(g.name)}</div><div class="username">${g.members.length} members · creator ${esc(person(g.creator).name)}</div></div><div class="form-label">Group name</div><input class="input" id="groupRename" value="${esc(g.name)}"/><button class="btn secondary wide" data-rename-group style="margin-top:8px">Rename group</button></div><div class="settings-section"><div class="settings-title">Group v3.5</div><div class="card settings-list">${toggleSetting('Everyone can rename','groupEveryone',g.everyoneRename)}${toggleSetting('Invite link enabled','groupInvite',g.inviteEnabled)}${toggleSetting('Announcements only','groupAnnouncements',g.announcementsOnly)}${toggleSetting('Allow member polls','groupPolls',g.allowPolls)}</div></div><div class="settings-section"><div class="settings-title">Invite</div><div class="card" style="padding:14px"><b>Code: ${esc(g.inviteCode||'—')}</b><div class="row gap8" style="margin-top:9px"><button class="btn secondary grow" data-rotate-invite>Rotate invite</button><button class="btn secondary grow" data-copy-invite>Copy</button></div></div></div><div class="settings-section"><div class="settings-title">Admin note</div><textarea class="textarea" id="adminNote">${esc(g.adminNote||'')}</textarea><button class="btn secondary wide" data-save-admin-note style="margin-top:8px">Save admin note</button></div><div class="settings-section"><div class="settings-title">Members</div><div class="card">${g.members.map(pid=>`<div class="setting">${avatar(person(pid),'sm')}<div class="grow"><strong>${esc(person(pid).name)}${pid===g.creator?' · Owner':''}</strong><small>${esc(person(pid).username)}</small></div>${pid!==state.meId&&state.meId===g.creator?`<button class="mini danger" data-remove-member="${pid}">Remove</button>`:''}</div>`).join('')}</div></div>${g.allowPolls?'<button class="btn secondary wide" data-create-poll>Create poll</button>':''}`)}
function toggleSetting(title,key,value){return `<div class="setting"><div class="grow"><strong>${esc(title)}</strong></div><button class="switch ${value?'on':''}" data-group-toggle="${key}"><span></span></button></div>`}
function messagePlusModal(){return modalShell('Message tools',`<div class="quickgrid"><button class="quick" data-message-tool="photo" style="text-align:left"><div class="qicon">${icon('camera',19)}</div><strong>Photo</strong><span>Local media placeholder.</span></button><button class="quick" data-message-tool="viewonce" style="text-align:left"><div class="qicon">◉</div><strong>View once</strong><span>Preview disposable media UI.</span></button><button class="quick" data-message-tool="voice" style="text-align:left"><div class="qicon">🎙️</div><strong>Voice</strong><span>Local voice-message preview.</span></button>${state.groups[currentChat]?.allowPolls?`<button class="quick" data-create-poll style="text-align:left"><div class="qicon">${icon('poll',19)}</div><strong>Poll</strong><span>Create a group poll.</span></button>`:''}</div>`)}
function plusModal(){return modalShell('LINK Plus',`<div class="plan-card plus"><div class="plan-title">LINK Plus</div><div class="plan-sub">More identity. More expression.</div>${['Custom Double Tap emoji','5 extra chat themes','More status colors & icons','15% profile-effect discount'].map(x=>`<div class="feature"><b>✓</b><span>${x}</span></div>`).join('')}</div><div class="row gap8"><button class="btn secondary grow" data-plan="free">Free</button><button class="btn primary grow" data-plan="plus">Activate locally</button></div>`)}
function proModal(){return modalShell('LINK Pro',`<div class="plan-card pro"><div class="plan-title">LINK Pro</div><div class="plan-sub">Everything in Plus — plus advanced identity, privacy and premium chat styles.</div>${['Premium chat themes','Offline (Ghost)','Silent Chat advanced timers','30% LINK Shop discount','Pro Insights preview','Premium presence styling'].map(x=>`<div class="feature"><b>✓</b><span>${x}</span></div>`).join('')}</div><div class="row gap8"><button class="btn secondary grow" data-plan="free">Free</button><button class="btn primary grow" data-plan="pro">Activate locally</button></div>`)}
function shopModal(){const p=me();return fullShell('LINK Shop',`<div class="row-between card" style="padding:14px;margin-bottom:12px"><div><div class="settings-title" style="margin:0">YOUR BALANCE</div><b style="font-size:23px">${p.coins||state.coins} Coins</b></div>${planBadge(p)}</div><div class="shop-grid">${PROFILE_EFFECTS.filter(x=>!x.staff||isStaff()).map(e=>{const owned=e.price===0||state.ownedEffects.includes(e.id),equipped=p.effect===e.id,discount=isPro()?.7:isPlus()?.85:1,price=Math.round(e.price*discount);return `<div class="card effect"><div class="effect-preview"><div class="fx-orb" style="--fx:${e.fx}">${e.id==='none'?'×':'✦'}</div></div><strong>${esc(e.name)}</strong><small>${e.staff?'Staff exclusive':owned?'Owned':isPro()?'30% Pro discount':isPlus()?'15% Plus discount':'Profile Effect'}</small><div class="price">${e.price?`${price} Coins`:'Free'}</div><button class="mini ${equipped?'':'primary'}" data-effect="${e.id}" style="margin-top:7px">${equipped?'Equipped':owned?'Use effect':'Buy'}</button></div>`}).join('')}</div>`)}
function statusModal(){const p=me();return fullShell('Custom status',`<div class="card status-preview"><div class="settings-title">Preview</div>${pillStatus(p)}</div><div class="form-label">Status text</div><input class="input" id="statusText" value="${esc(p.statusText||'')}" maxlength="50"/><div class="form-label">Icon</div><div class="emoji-grid">${STATUS_EMOJIS.map(e=>`<button class="emoji-choice ${p.statusEmoji===e?'active':''}" data-status-emoji="${e}">${e}</button>`).join('')}</div><div class="form-label">Solid color</div><div class="color-grid">${STATUS_COLORS.map(c=>`<button class="swatch ${p.statusColor===c&&!p.statusGradient?'active':''}" data-status-color="${c}" style="background:${c}"></button>`).join('')}</div>${isStaff()?`<div class="form-label">Gradient · 40</div><div class="color-grid">${STATUS_GRADIENTS.map(([gid,cols])=>`<button class="swatch ${p.statusGradient===gid?'active':''}" data-status-gradient="${gid}" style="background:linear-gradient(135deg,${cols.join(',')})"></button>`).join('')}</div>`:''}<button class="btn primary wide" data-save-status style="margin-top:14px">Save status</button>`)}
function doubleTapModal(){return modalShell('Double Tap reaction',`<div class="sheet-sub">Double tap any message to add your selected emoji.</div><div class="emoji-grid">${DOUBLE_TAP.map(e=>`<button class="emoji-choice ${state.settings.doubleTap===e?'active':''}" data-double-emoji="${e}">${e}</button>`).join('')}</div><div class="form-label">Or paste any emoji</div><input class="input" id="doubleCustom" value="${esc(state.settings.doubleTap)}"/><button class="btn primary wide" data-save-double style="margin-top:10px">Save Double Tap reaction</button>`)}
function safetyModal(){return fullShell(t('Safety Center'),`<div class="settings-section"><div class="settings-title">Blocked accounts</div><div class="card">${state.blocked.map(pid=>`<div class="setting">${avatar(person(pid),'sm')}<div class="grow"><strong>${esc(person(pid).name)}</strong><small>${esc(person(pid).username)}</small></div><button class="mini" data-unblock="${pid}">Unblock</button></div>`).join('')||'<div class="empty"><strong>No blocked accounts</strong>Your block list is empty.</div>'}</div></div><div class="settings-section"><div class="settings-title">Security</div><div class="card settings-list">${settingRow('Login alerts',state.settings.loginAlerts?'On':'Off','bell','loginAlerts')}${settingRow('Devices','This PWA only','profile','devices')}${settingRow('Change password','Backend required','lock','noBackend')}</div></div><div class="settings-section"><div class="settings-title">Reports</div><div class="card"><div class="setting"><div class="grow"><strong>${state.reports.length} local reports</strong><small>Stored only on this device.</small></div></div></div></div>`)}
function accountsModal(){return fullShell(t('Local accounts'),`<div class="sheet-sub">Solo testing account manager — no Supabase Auth.</div><div class="card">${state.accounts.map(pid=>{const p=person(pid);return `<button class="person" data-switch-account="${pid}" style="width:100%;border:0;background:none;color:inherit;text-align:left">${avatar(p,'sm')}<div class="grow"><h3>${esc(p.name)}${verify(p)}</h3><div class="sub">${esc(p.username)}${pid===state.meId?' · Active':''}</div></div>${pid===state.meId?'<span class="pill green">ACTIVE</span>':''}</button>`}).join('')}</div><button class="btn primary wide" data-add-account style="margin-top:12px">Add local test account</button>`)}
function staffModal(){return fullShell('Staff Center',`<div class="hero"><div class="hero-eyebrow">LOCAL STAFF PREVIEW</div><h1>LINK Staff Center</h1><p>Moderation and official-message tools are simulated locally.</p></div><div class="settings-section"><div class="settings-title">Official message</div><textarea class="textarea" id="officialText" placeholder="Message from LINK Official"></textarea><button class="btn primary wide" data-send-official style="margin-top:8px">Send locally as LINK Official</button></div><div class="settings-section"><div class="settings-title">Accounts</div><div class="card">${Object.values(state.profiles).filter(p=>p.id!==state.meId).map(p=>`<div class="setting">${avatar(p,'sm')}<div class="grow"><strong>${esc(p.name)}</strong><small>${esc(p.username)}</small></div><button class="mini" data-staff-mute="${p.id}">Mute</button><button class="mini danger" data-staff-ban="${p.id}">Ban</button></div>`).join('')}</div></div>`)}
function threadModal(){const root=state.posts.find(x=>x.id===overlay.id);if(!root)return'';const replies=state.posts.filter(x=>x.replyTo===root.id&&!x.deleted);return fullShell('Thread',`${postCard(root)}<div class="sectionhead"><h2>Replies</h2></div>${replies.length?feedPosts(replies):'<div class="empty"><strong>No replies yet</strong>Start the thread.</div>'}<button class="btn primary wide" data-reply-post="${root.id}">Write a reply</button>`)}
function postMenuModal(){const p=state.posts.find(x=>x.id===overlay.id);if(!p)return'';const mine=p.author===state.meId;return modalShell('Post',`<div class="card settings-list">${settingRow('Open thread','Replies and conversation','comment','openThread')}${settingRow('Quote post','Add your take','repeat','quotePost')}${mine?settingRow(p.pinned?'Unpin from profile':'Pin to profile','Profile posts','pin','pinPost'):''}${mine?settingRow('Delete post','Remove locally','trash','deletePost'):settingRow('Report post','Local safety report','shield','reportPost')}</div>`)}
function reportModal(){const p=person(overlay.id);return modalShell('Report',`<div class="sheet-sub">Report ${esc(p.name)}. In solo mode this stays only on your device.</div><select class="select" id="reportReason"><option>Spam</option><option>Harassment</option><option>Impersonation</option><option>Unsafe content</option><option>Other</option></select><textarea class="textarea" id="reportDetails" placeholder="Optional details" style="margin-top:9px"></textarea><button class="btn danger wide" data-submit-report style="margin-top:9px">Submit local report</button>`)}
function scanModal(){return fullShell('Scan a LINK',`<div class="center card" style="padding:24px"><div style="font-size:70px">▦</div><h2>Camera scanner preview</h2><p class="muted" style="font-size:12px;line-height:1.45">The LINK 4.4 camera/QR UI is preserved. This backend-free PWA can’t resolve remote LINK identities, so use a local @username below.</p><input class="input" id="scanUser" placeholder="@username"/><button class="btn primary wide" data-simulate-scan style="margin-top:9px">Simulate scan</button></div>`)}
function installModal(){return modalShell('Install LINK PWA',`<div class="card" style="padding:14px"><b>iPhone / iPad</b><p class="muted" style="font-size:11.5px;line-height:1.45">Open this site in Safari → Share → Add to Home Screen.</p><button class="btn primary wide" data-native-install>Install / show prompt</button></div>`)}
function settingsModal(){const p=me();return fullShell(t('LINK Settings'),`${settingsSection('Profile',settingRow('Profile layout',p.profileLayout||'Default','profile','layout')+settingRow('Profile effects',PROFILE_EFFECTS.find(x=>x.id===p.effect)?.name||'None','spark','shop')+settingRow('Active status',p.presence,'globe','presence')+settingRow('Custom status',p.statusText||'—','palette','status')+settingRow('Double Tap reaction',isPlus()?state.settings.doubleTap:'❤️','heart',isPlus()?'doubleTap':'plus'))}${settingsSection('Subscription',settingRow('LINK Pro',p.plan==='pro'?'Active':'Inactive','spark','pro')+settingRow('LINK Plus',p.plan==='plus'?'Active':p.plan==='pro'?'Included':'Inactive','spark','plus'))}${isStaff()?settingsSection('Administration',settingRow('Staff Center',p.role==='ceo'?'CEO':'Admin','shield','staff')+settingRow('Staff Badge','Local preview','spark','staffBadge')):''}${settingsSection('Account',settingRow('Display name',p.name,'profile','')+settingRow('Username',p.username,'profile','')+settingRow('Local account','Solo session','lock','accounts'))}${settingsSection('Privacy',privacyRows())}${settingsSection('Sharing',toggleRow('Share custom status','showStatus')+toggleRow('Show socials','showSocials')+toggleRow('Moments to LINKs','momentsToLinks'))}${settingsSection('Notifications',toggleRow('Messages','notifMessages')+toggleRow('LINK requests','notifRequests')+toggleRow('Moments','notifMoments')+toggleRow('LINK updates','notifProduct'))}${settingsSection('Security',settingRow('Safety Center','Block, reports and local devices','shield','safety')+toggleRow('Login alerts','loginAlerts'))}${settingsSection('Appearance',settingRow('Theme',state.theme,'palette','theme')+settingRow('Language',state.language==='cs'?'Čeština':'English','globe','language'))}${settingsSection('Solo testing',toggleDevRow()+settingRow('Install PWA','Add to Home Screen','plus','install')+settingRow('Reset demo data','Restore Full Solo defaults','trash','reset'))}`)}
function settingsSection(title,body){return `<div class="settings-section"><div class="settings-title">${esc(title)}</div><div class="card settings-list">${body}</div></div>`}
function toggleRow(title,key){return `<div class="setting"><div class="grow"><strong>${esc(title)}</strong></div><button class="switch ${state.settings[key]?'on':''}" data-setting-toggle="${key}"><span></span></button></div>`}
function toggleDevRow(){return `<div class="setting"><div class="grow"><strong>Staff tools preview</strong><small>Expose admin/CEO-only UI locally.</small></div><button class="switch ${state.dev.staffPreview?'on':''}" data-dev-toggle><span></span></button></div>`}
function privacyRows(){const choices=[['Profile visibility','profileVisibility',state.settings.profileVisibility],['Messages from','messagesFrom',state.settings.messagesFrom],['LINK requests','linkRequestsFrom',state.settings.linkRequestsFrom]];return choices.map(([l,k,v])=>`<button class="setting" data-choice="${k}" style="width:100%;border:0;background:none;color:inherit;text-align:left"><div class="grow"><strong>${l}</strong></div><span class="setting-value">${esc(v)}</span><span class="chev">›</span></button>`).join('')+toggleRow('Show activity status','showActivity')+toggleRow('Show last active','showLastActive')+toggleRow('Read receipts','readReceipts')+toggleRow('Typing indicators','typing')+toggleRow('Profile views','profileViews')+toggleRow('Discoverable by username','discoverUsername')+toggleRow('Discoverable by email','discoverEmail')}
function messageContext(){const g=state.groups[currentChat],list=g?(g.messages||[]):(state.messages[currentChat]||[]),m=list.find(x=>x.id===contextMsg);if(!m){contextMsg=null;return''}const mine=m.from===state.meId;return `<div class="modalback" data-context-backdrop><div class="context-menu"><div class="row gap6 wrap" style="padding:7px 5px 10px">${DOUBLE_TAP.slice(0,7).map(e=>`<button class="emoji-choice" data-react-msg="${e}" style="width:38px;height:38px">${e}</button>`).join('')}</div><button class="context-row" data-msg-action="reply">${icon('comment',18)} Reply</button>${mine?`<button class="context-row" data-msg-action="edit">${icon('edit',18)} Edit</button>`:''}<button class="context-row" data-msg-action="pin">${icon('pin',18)} ${m.pinned?'Unpin':'Pin'} message</button><button class="context-row" data-msg-action="forward">${icon('send',18)} Forward</button>${mine?`<button class="context-row danger" data-msg-action="deleteEveryone">${icon('trash',18)} Delete for everyone</button>`:''}<button class="context-row danger" data-msg-action="deleteMe">${icon('trash',18)} Delete for me</button></div></div>`}
function bind(){
 qsa('[data-tab]').forEach(b=>b.onclick=()=>{if(b.dataset.tab==='create'){overlay={type:'createHub'};renderCreateHub();return}state.tab=b.dataset.tab;save();app()});
 qsa('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open));
 qsa('[data-profile]').forEach(b=>b.onclick=e=>{e.stopPropagation();overlay={type:'profile',id:b.dataset.profile};app()});
 qsa('[data-chat]').forEach(b=>b.onclick=()=>{currentChat=b.dataset.chat;overlay=null;contextMsg=null;replyingTo=null;app();setTimeout(scrollChat,0)});
 qsa('[data-moment]').forEach(b=>b.onclick=()=>{currentMoment=b.dataset.moment;app()});
 qsa('[data-note]').forEach(b=>b.onclick=()=>{overlay={type:'noteView',id:b.dataset.note};app()});
 qsa('[data-like]').forEach(b=>b.onclick=e=>{e.stopPropagation();togglePostArray(b.dataset.like,'likes');app()});
 qsa('[data-bookmark]').forEach(b=>b.onclick=e=>{e.stopPropagation();togglePostArray(b.dataset.bookmark,'bookmarks');app()});
 qsa('[data-repost]').forEach(b=>b.onclick=e=>{e.stopPropagation();togglePostArray(b.dataset.repost,'reposts');app()});
 qsa('[data-reply-post]').forEach(b=>b.onclick=e=>{e.stopPropagation();overlay={type:'post',replyTo:b.dataset.replyPost};app()});
 qsa('[data-post-menu]').forEach(b=>b.onclick=e=>{e.stopPropagation();overlay={type:'postMenu',id:b.dataset.postMenu};app()});
 qsa('[data-post]').forEach(b=>b.onclick=e=>{if(e.target.closest('button'))return;overlay={type:'thread',id:b.dataset.post};app()});
 qsa('[data-accept]').forEach(b=>b.onclick=()=>{const r=state.requests.find(x=>x.id===b.dataset.accept);if(r&&!state.connected.includes(r.from))state.connected.push(r.from);state.requests=state.requests.filter(x=>x.id!==b.dataset.accept);save();toast('LINK request accepted');app()});
 qsa('[data-decline]').forEach(b=>b.onclick=()=>{state.requests=state.requests.filter(x=>x.id!==b.dataset.decline);save();app()});
 qsa('[data-profile-tab]').forEach(b=>b.onclick=()=>{state.profileTab=b.dataset.profileTab;save();app()});
 const ds=qs('#discoverSearch');if(ds)ds.oninput=()=>filterDiscover(ds.value);
 qsa('[data-trend]').forEach(b=>b.onclick=()=>{if(ds){ds.value=b.dataset.trend;filterDiscover(ds.value)}});
 bindOverlay();bindChat();bindMoment();edgeSwipe();
}
function open(type){if(type==='search'||type==='activity'||type==='whatsnew'||type==='pulse'||type==='mylink'||type==='note'||type==='moment'||type==='post'||type==='backstage'||type==='settings'||type==='editprofile'||type==='newgroup'||type==='plus'||type==='pro'||type==='shop'||type==='status'||type==='doubleTap'||type==='safety'||type==='accounts'||type==='staff'||type==='qrscan'||type==='install'){overlay={type};app();return}if(type==='create'){renderCreateHub();return}}
function renderCreateHub(){overlay={type:'createHub'};app()}
function createHubModal(){return modalShell('Create',`<div class="quickgrid"><button class="quick" data-hub="post" style="text-align:left"><div class="qicon">${icon('feed')}</div><strong>Post</strong><span>Permanent profile post.</span></button><button class="quick" data-hub="moment" style="text-align:left"><div class="qicon">◎</div><strong>Moment</strong><span>24-hour visual update.</span></button><button class="quick" data-hub="note" style="text-align:left"><div class="qicon">✎</div><strong>Note</strong><span>Short status above Feed.</span></button><button class="quick" data-hub="newgroup" style="text-align:left"><div class="qicon">${icon('users')}</div><strong>Group</strong><span>Create local group chat.</span></button><button class="quick" data-hub="pulse" style="text-align:left"><div class="qicon">◉</div><strong>LINK Now</strong><span>Live identity on Pulse.</span></button><button class="quick" data-hub="mylink" style="text-align:left"><div class="qicon">${icon('qr')}</div><strong>My LINK</strong><span>Show your LINK card.</span></button></div>`)}
const _renderOverlay=renderOverlay;renderOverlay=function(){if(overlay?.type==='createHub')return createHubModal();return _renderOverlay()}
function bindOverlay(){
 qsa('[data-close-overlay]').forEach(b=>b.onclick=()=>{overlay=null;app()});
 const bd=qs('[data-backdrop]');if(bd)bd.onclick=e=>{if(e.target===bd){overlay=null;app()}};
 qsa('[data-hub]').forEach(b=>b.onclick=()=>{overlay={type:b.dataset.hub};app()});
 const gs=qs('#globalSearch');if(gs){const run=()=>renderGlobalSearch(gs.value);gs.oninput=run;setTimeout(()=>gs.focus(),60);run()}
 qsa('[data-read-all]').forEach(b=>b.onclick=()=>{state.notifications.forEach(n=>n.read=true);save();app()});
 qsa('[data-activity]').forEach(b=>b.onclick=()=>{const n=state.notifications.find(x=>x.id===b.dataset.activity);if(n){n.read=true;save();if(n.postId){overlay={type:'thread',id:n.postId}}else if(n.type==='link')state.tab='discover';app()}});
 on('[data-save-pulse]',()=>{state.linkNow[state.meId]={text:qs('#pulseText').value.trim()||'Online',emoji:qs('#pulseEmoji').value.trim()||'✨'};me().statusText=state.linkNow[state.meId].text;me().statusEmoji=state.linkNow[state.meId].emoji;save();overlay=null;toast('LINK Now updated');app()});
 on('[data-share-link]',async()=>{const p=me(),text=`Find me on LINK: ${p.username}`;try{if(navigator.share)await navigator.share({title:'My LINK',text});else{await navigator.clipboard.writeText(text);toast('Copied') }}catch{}});
 on('[data-save-note]',()=>{const text=qs('#noteText').value.trim(),aud=qs('#noteAudience').value;state.notes=state.notes.filter(x=>x.owner!==state.meId);if(text)state.notes.unshift({id:id('note'),owner:state.meId,text,audience:aud,createdAt:now()});save();overlay=null;toast('Note saved');app()});
 on('[data-delete-note]',()=>{state.notes=state.notes.filter(x=>x.owner!==state.meId);save();overlay=null;app()});
 on('[data-note-reply]',()=>{const n=state.notes.find(x=>x.id===qs('[data-note-reply]').dataset.noteReply);if(n){currentChat=n.owner;state.messages[currentChat]=state.messages[currentChat]||[];state.drafts[currentChat]=`Re: “${n.text}” `;overlay=null;app();setTimeout(()=>qs('#composer')?.focus(),50)}});
 on('[data-save-moment]',()=>{const cap=qs('#momentCaption').value.trim()||'Moment',emoji=qs('#momentEmoji').value.trim()||'✨',music=qs('#momentMusic').value.trim(),aud=qs('#momentAudience').value;state.moments.unshift({id:id('moment'),owner:state.meId,caption:cap,emoji,music,audience:aud,createdAt:now(),viewCount:0});save();overlay=null;toast('Moment posted locally');app()});
 on('[data-save-post]',()=>{const text=qs('#postText').value.trim(),media=qs('#postMedia').value.trim();if(!text&&!media)return toast('Write something first');state.posts.unshift({id:id('post'),author:state.meId,text,media:media||null,createdAt:now(),likes:[],reposts:[],bookmarks:[],replyTo:overlay.replyTo||null,quoteOf:overlay.quoteOf||null});const wasReply=!!overlay.replyTo;save();overlay=null;toast(wasReply?'Reply posted':'Posted');app()});
 on('[data-save-profile]',()=>{const p=me();p.name=qs('#editName').value.trim()||p.name;p.username='@'+qs('#editUser').value.trim().replace(/^@/,'').replace(/\s/g,'').toLowerCase();p.bio=qs('#editBio').value.trim();p.instagram=qs('#editInstagram').value.trim();p.spotify=qs('#editSpotify').value.trim();p.website=qs('#editWebsite').value.trim();save();overlay=null;app()});
 const selected=new Set();qsa('[data-member]').forEach(b=>b.onclick=()=>{const k=b.dataset.member;selected.has(k)?selected.delete(k):selected.add(k);b.querySelector('.pill').textContent=selected.has(k)?'Added':'Add';b.querySelector('.pill').classList.toggle('accent',selected.has(k))});
 on('[data-create-group]',()=>{const gid=id('group'),name=qs('#groupName').value.trim()||'New Group';state.groups[gid]={id:gid,name,members:[state.meId,...selected],creator:state.meId,everyoneRename:false,inviteEnabled:true,inviteCode:Math.random().toString(36).slice(2,8).toUpperCase(),announcementsOnly:false,slowMode:0,allowPolls:true,adminNote:'',theme:'default',messages:[{id:id('msg'),from:state.meId,text:'Group created locally.',at:now(),read:true}],polls:[]};state.chatThemes[gid]='default';save();overlay=null;currentChat=gid;app()});
 on('[data-open-person-chat]',()=>{currentChat=qs('[data-open-person-chat]').dataset.openPersonChat;state.messages[currentChat]=state.messages[currentChat]||[];overlay=null;app()});
 on('[data-link-request]',()=>{const pid=qs('[data-link-request]').dataset.linkRequest;if(!state.connected.includes(pid)){state.connected.push(pid);toast('Local LINK added instantly for solo testing')}save();overlay=null;app()});
 on('[data-unlink]',()=>{const pid=qs('[data-unlink]').dataset.unlink;state.connected=state.connected.filter(x=>x!==pid);save();overlay=null;app()});
 on('[data-favorite]',()=>{const pid=qs('[data-favorite]').dataset.favorite;state.favorites.includes(pid)?state.favorites=state.favorites.filter(x=>x!==pid):state.favorites.push(pid);save();app()});
 on('[data-block]',()=>{const pid=qs('[data-block]').dataset.block;state.blocked.includes(pid)?state.blocked=state.blocked.filter(x=>x!==pid):state.blocked.push(pid);save();overlay=null;app()});
 on('[data-report]',()=>{overlay={type:'report',id:qs('[data-report]').dataset.report};app()});
 on('[data-submit-report]',()=>{state.reports.push({id:id('report'),target:overlay.id,reason:qs('#reportReason').value,details:qs('#reportDetails').value.trim(),at:now()});save();overlay=null;toast('Saved as local report');app()});
 qsa('[data-chat-theme]').forEach(b=>b.onclick=()=>{const x=CHAT_THEMES.find(t=>t.id===b.dataset.chatTheme),allowed=x.tier==='free'||x.tier==='plus'&&isPlus()||x.tier==='pro'&&isPro();if(!allowed){overlay={type:x.tier==='pro'?'pro':'plus'};app();return}state.chatThemes[currentChat]=x.id;save();overlay=null;app()});
 qsa('[data-locked-theme]').forEach(b=>b.onclick=()=>{});
 qsa('[data-setting-action]').forEach(b=>b.onclick=()=>settingAction(b.dataset.settingAction));
 qsa('[data-group-toggle]').forEach(b=>b.onclick=()=>{const g=state.groups[currentChat],k=b.dataset.groupToggle,map={groupEveryone:'everyoneRename',groupInvite:'inviteEnabled',groupAnnouncements:'announcementsOnly',groupPolls:'allowPolls'};g[map[k]]=!g[map[k]];save();app()});
 on('[data-rename-group]',()=>{const g=state.groups[currentChat],v=qs('#groupRename').value.trim();if(v)g.name=v;save();overlay=null;app()});
 on('[data-rotate-invite]',()=>{state.groups[currentChat].inviteCode=Math.random().toString(36).slice(2,8).toUpperCase();save();app()});
 on('[data-copy-invite]',async()=>{const code=state.groups[currentChat].inviteCode;try{await navigator.clipboard.writeText(code);toast('Invite code copied')}catch{toast(code)}});
 on('[data-save-admin-note]',()=>{state.groups[currentChat].adminNote=qs('#adminNote').value.trim();save();toast('Admin note saved')});
 qsa('[data-remove-member]').forEach(b=>b.onclick=()=>{const g=state.groups[currentChat];g.members=g.members.filter(x=>x!==b.dataset.removeMember);save();app()});
 qsa('[data-message-tool]').forEach(b=>b.onclick=()=>{const type=b.dataset.messageTool,txt=type==='photo'?'📷 Photo · local preview':type==='viewonce'?'◉ View once media · local preview':'🎙️ Voice message · 0:12';sendMessage(txt);overlay=null;app()});
 on('[data-create-poll]',()=>createPoll());
 qsa('[data-plan]').forEach(b=>b.onclick=()=>{me().plan=b.dataset.plan;save();overlay=null;toast(`Plan set to ${me().plan.toUpperCase()} locally`);app()});
 qsa('[data-effect]').forEach(b=>b.onclick=()=>{const e=PROFILE_EFFECTS.find(x=>x.id===b.dataset.effect);if(!e)return;const p=me(),owned=e.price===0||state.ownedEffects.includes(e.id);if(!owned){const factor=isPro()?.7:isPlus()?.85:1,price=Math.round(e.price*factor);if((p.coins||state.coins)<price)return toast('Not enough LINK Coins');p.coins=(p.coins||state.coins)-price;state.ownedEffects.push(e.id);toast('Profile effect purchased')}p.effect=e.id;save();app()});
 qsa('[data-status-emoji]').forEach(b=>b.onclick=()=>{me().statusEmoji=b.dataset.statusEmoji;save();app()});qsa('[data-status-color]').forEach(b=>b.onclick=()=>{me().statusColor=b.dataset.statusColor;me().statusGradient=null;save();app()});qsa('[data-status-gradient]').forEach(b=>b.onclick=()=>{me().statusGradient=b.dataset.statusGradient;save();app()});
 on('[data-save-status]',()=>{me().statusText=qs('#statusText').value.trim()||'Online';save();overlay=null;app()});qsa('[data-double-emoji]').forEach(b=>b.onclick=()=>{state.settings.doubleTap=b.dataset.doubleEmoji;save();app()});on('[data-save-double]',()=>{state.settings.doubleTap=qs('#doubleCustom').value.trim()||state.settings.doubleTap;save();overlay=null;app()});
 qsa('[data-unblock]').forEach(b=>b.onclick=()=>{state.blocked=state.blocked.filter(x=>x!==b.dataset.unblock);save();app()});
 qsa('[data-switch-account]').forEach(b=>b.onclick=()=>{state.meId=b.dataset.switchAccount;save();overlay=null;app()});
 on('[data-add-account]',()=>addAccount());
 on('[data-send-official]',()=>{const text=qs('#officialText').value.trim();if(!text)return;state.messages.link=state.messages.link||[];state.messages.link.push({id:id('msg'),from:'link',text,at:now(),read:false});state.officialAnnouncements.unshift({id:id('oa'),title:'LINK Official',body:text,at:now(),read:false});save();toast('Official message created locally');app()});
 qsa('[data-staff-mute]').forEach(b=>b.onclick=()=>toast(`${person(b.dataset.staffMute).username} muted locally`));qsa('[data-staff-ban]').forEach(b=>b.onclick=()=>toast(`${person(b.dataset.staffBan).username} banned locally`));
 qsa('[data-setting-toggle]').forEach(b=>b.onclick=()=>{state.settings[b.dataset.settingToggle]=!state.settings[b.dataset.settingToggle];save();app()});on('[data-dev-toggle]',()=>{state.dev.staffPreview=!state.dev.staffPreview;save();app()});
 qsa('[data-choice]').forEach(b=>b.onclick=()=>cycleChoice(b.dataset.choice));
 on('[data-native-install]',async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else toast('iOS: Safari → Share → Add to Home Screen')});
 on('[data-simulate-scan]',()=>{const u=qs('#scanUser').value.trim().toLowerCase();const p=Object.values(state.profiles).find(x=>x.username.toLowerCase()===u);if(!p)return toast('No local account found');overlay={type:'profile',id:p.id};app()});
 qsa('[data-msg-action]').forEach(b=>b.onclick=()=>msgAction(b.dataset.msgAction));qsa('[data-react-msg]').forEach(b=>b.onclick=()=>{reactMessage(b.dataset.reactMsg);contextMsg=null;app()});
 on('[data-random-photo]',()=>toast('Image picker is intentionally omitted in static solo ZIP.'));
}
function on(sel,fn){const e=qs(sel);if(e)e.onclick=fn}
function bindChat(){
 on('[data-chat-close]',()=>{currentChat=null;contextMsg=null;replyingTo=null;app()});on('[data-open-chat-theme]',()=>{overlay={type:'chatTheme'};app()});on('[data-open-chat-info]',()=>{overlay={type:'chatInfo'};app()});on('[data-group-settings]',()=>{overlay={type:'groupSettings'};app()});on('[data-chat-plus]',()=>{overlay={type:'messagePlus'};app()});on('[data-cancel-reply]',()=>{replyingTo=null;app()});
 const c=qs('#composer');if(c){c.oninput=()=>{state.drafts[currentChat]=c.value;save()};c.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage(c.value)}}}on('[data-send]',()=>sendMessage(qs('#composer')?.value));
 qsa('[data-msg-context]').forEach(b=>{let timer;b.oncontextmenu=e=>{e.preventDefault();contextMsg=b.dataset.msgContext;app()};b.ontouchstart=()=>{timer=setTimeout(()=>{contextMsg=b.dataset.msgContext;app()},500)};b.ontouchend=()=>clearTimeout(timer);b.ontouchmove=()=>clearTimeout(timer)});
 qsa('[data-dbl-msg]').forEach(b=>{let last=0;b.onclick=()=>{const n=Date.now();if(n-last<330){reactMessage(state.settings.doubleTap||'❤️');last=0;app()}else last=n}});
 qsa('[data-vote]').forEach(b=>b.onclick=()=>{const [pid,idx]=b.dataset.vote.split(':'),g=state.groups[currentChat],p=g.polls.find(x=>x.id===pid);p.votes=p.votes||{};p.votes[state.meId]=Number(idx);save();app()});
 setTimeout(scrollChat,0);
}
function bindMoment(){on('[data-close-moment]',()=>{currentMoment=null;app()});qsa('[data-moment-react]').forEach(b=>b.onclick=()=>toast(`${b.dataset.momentReact} reaction sent locally`));on('[data-moment-reply]',()=>{const m=state.moments.find(x=>x.id===currentMoment);if(m&&m.owner!==state.meId){currentChat=m.owner;state.messages[currentChat]=state.messages[currentChat]||[];state.drafts[currentChat]=`Replying to your Moment “${m.caption}” `;currentMoment=null;app()}});on('[data-highlight-moment]',()=>{const m=state.moments.find(x=>x.id===currentMoment);state.highlights.push({id:id('h'),name:m.caption.slice(0,12),emoji:m.emoji||'✨'});save();toast('Added to Highlights');currentMoment=null;app()});on('[data-repost-moment]',()=>toast('Moment repost preview'))}
function settingAction(a){if(a==='shop')overlay={type:'shop'};else if(a==='status')overlay={type:'status'};else if(a==='doubleTap')overlay={type:'doubleTap'};else if(a==='plus')overlay={type:'plus'};else if(a==='pro')overlay={type:'pro'};else if(a==='accounts')overlay={type:'accounts'};else if(a==='staff')overlay={type:'staff'};else if(a==='safety')overlay={type:'safety'};else if(a==='install')overlay={type:'install'};else if(a==='groupSettings')overlay={type:'groupSettings'};else if(a==='chatTheme')overlay={type:'chatTheme'};else if(a==='silent'){if(!isPro()){overlay={type:'pro'}}else{const cur=state.silentChats[currentChat]||0;state.silentChats[currentChat]=cur===0?10:cur===10?3600:cur===3600?604800:0;save();toast(`Silent Chat ${state.silentChats[currentChat]?state.silentChats[currentChat]+'s':'off'}`)}}else if(a==='encryption')toast('Solo PWA: messages stay on this device; production E2E requires backend/key exchange.');else if(a==='markUnread'){const list=state.groups[currentChat]?.messages||state.messages[currentChat]||[];const last=[...list].reverse().find(m=>m.from!==state.meId);if(last)last.read=false;save();toast('Marked unread') }else if(a==='archiveChat')toast('Archive preview saved locally');else if(a==='theme'){state.theme=state.theme==='system'?'light':state.theme==='light'?'dark':'system';save()}else if(a==='language'){state.language=state.language==='en'?'cs':'en';save()}else if(a==='presence'){const order=['online','dnd','busy','ghost'];let idx=order.indexOf(me().presence);let next=order[(idx+1)%order.length];if(next==='ghost'&&!isPro())overlay={type:'pro'};else me().presence=next;save()}else if(a==='reset'){if(confirm('Reset all LINK PWA local data?')){localStorage.removeItem(STORE);state=seed();overlay=null;currentChat=null;save();toast('Demo reset')}}else if(a==='openThread'){overlay={type:'thread',id:overlay.id}}else if(a==='quotePost'){overlay={type:'post',quoteOf:overlay.id}}else if(a==='pinPost'){const p=state.posts.find(x=>x.id===overlay.id);p.pinned=!p.pinned;save();overlay=null}else if(a==='deletePost'){const p=state.posts.find(x=>x.id===overlay.id);p.deleted=true;save();overlay=null}else if(a==='reportPost'){toast('Post report saved locally');overlay=null}else if(a==='noBackend')toast('Backend-required action disabled in Solo mode.');app()}
function cycleChoice(k){const options=k==='profileVisibility'?['everyone','links','private']:k==='messagesFrom'?['everyone','links','nobody']:['everyone','mutuals','nobody'];const i=options.indexOf(state.settings[k]);state.settings[k]=options[(i+1)%options.length];save();app()}
function sendMessage(text){text=String(text||'').trim();if(!text)return;const g=state.groups[currentChat],m={id:id('msg'),from:state.meId,text,at:now(),read:true,replyTo:replyingTo?.id||null};if(g)g.messages.push(m);else{state.messages[currentChat]=state.messages[currentChat]||[];state.messages[currentChat].push(m)}state.drafts[currentChat]='';replyingTo=null;save();app();setTimeout(scrollChat,0)}
function scrollChat(){const el=qs('#chatBody');if(el)el.scrollTop=el.scrollHeight}
function currentMessage(){const g=state.groups[currentChat],list=g?(g.messages||[]):(state.messages[currentChat]||[]);return list.find(x=>x.id===contextMsg)}
function reactMessage(e){const m=currentMessage();if(m)m.reaction=m.reaction===e?null:e;save()}
function msgAction(a){const m=currentMessage();if(!m)return;if(a==='reply'){replyingTo=m;contextMsg=null}else if(a==='edit'){const v=prompt('Edit message',m.text);if(v!==null&&v.trim()){m.text=v.trim();m.edited=true;contextMsg=null}}else if(a==='pin'){m.pinned=!m.pinned;contextMsg=null}else if(a==='forward'){const target=Object.keys(state.messages).find(x=>x!==currentChat)||'noa';state.messages[target]=state.messages[target]||[];state.messages[target].push({id:id('msg'),from:state.meId,text:`Forwarded: ${m.text}`,at:now(),read:true,forwarded:true});contextMsg=null;toast(`Forwarded to ${person(target).name}`)}else if(a==='deleteEveryone'){m.deletedEveryone=true;m.text='Message deleted';contextMsg=null}else if(a==='deleteMe'){m.deletedForMe=true;contextMsg=null}save();app()}
function togglePostArray(pid,key){const p=state.posts.find(x=>x.id===pid);if(!p)return;p[key]=p[key]||[];p[key].includes(state.meId)?p[key]=p[key].filter(x=>x!==state.meId):p[key].push(state.meId);save()}
function filterDiscover(q){q=String(q||'').toLowerCase().trim();const people=Object.values(state.profiles).filter(p=>p.id!==state.meId&&`${p.name} ${p.username} ${p.bio||''}`.toLowerCase().includes(q.replace(/^#/,' ')));const posts=state.posts.filter(p=>`${p.text} ${p.tag||''}`.toLowerCase().includes(q.replace(/^#/,'').trim()));qs('#peopleResults').innerHTML=peopleList(q?people:Object.values(state.profiles).filter(p=>!state.connected.includes(p.id)&&p.id!==state.meId&&p.id!=='link'));qs('#discoverPosts').innerHTML=feedPosts(q?posts:state.posts.filter(p=>p.author!==state.meId).slice().sort((a,b)=>(b.likes?.length||0)-(a.likes?.length||0)));qsa('[data-profile]').forEach(b=>b.onclick=()=>{overlay={type:'profile',id:b.dataset.profile};app()});qsa('[data-like]').forEach(b=>b.onclick=()=>{togglePostArray(b.dataset.like,'likes');app()})}
function renderGlobalSearch(q){q=String(q||'').trim().toLowerCase();const host=qs('#searchResults');if(!host)return;if(!q){host.innerHTML='<div class="empty"><strong>Search LINK</strong>People, posts, groups and chats.</div>';return}const people=Object.values(state.profiles).filter(p=>`${p.name} ${p.username}`.toLowerCase().includes(q)),posts=state.posts.filter(p=>p.text.toLowerCase().includes(q)).slice(0,6),groups=Object.values(state.groups).filter(g=>g.name.toLowerCase().includes(q));host.innerHTML=`${people.length?`<div class="settings-title">People</div><div class="card">${peopleList(people)}</div>`:''}${groups.length?`<div class="settings-title" style="margin-top:14px">Groups</div><div class="card">${groups.map(g=>chatRow({type:'group',id:g.id})).join('')}</div>`:''}${posts.length?`<div class="settings-title" style="margin-top:14px">Posts</div>${feedPosts(posts)}`:''}${!people.length&&!groups.length&&!posts.length?'<div class="empty"><strong>No results</strong>Try another query.</div>':''}`;qsa('[data-profile]').forEach(b=>b.onclick=()=>{overlay={type:'profile',id:b.dataset.profile};app()});qsa('[data-chat]').forEach(b=>b.onclick=()=>{currentChat=b.dataset.chat;overlay=null;app()});qsa('[data-post]').forEach(b=>b.onclick=e=>{if(e.target.closest('button'))return;overlay={type:'thread',id:b.dataset.post};app()})}
function createPoll(){const q=prompt('Poll question');if(!q)return;const opts=prompt('Options, separated by commas','Yes,No,Maybe');if(!opts)return;const g=state.groups[currentChat];if(!g)return;g.polls=g.polls||[];g.polls.push({id:id('poll'),question:q,options:opts.split(',').map(x=>x.trim()).filter(Boolean).slice(0,5),votes:{}});save();overlay=null;app()}
function addAccount(){const name=prompt('Display name');if(!name)return;const username=prompt('Username','@testaccount')||'@testaccount';const pid=id('account');state.profiles[pid]={id:pid,name,username:'@'+username.replace(/^@/,'').replace(/\s/g,'').toLowerCase(),bio:'Local LINK test account',verified:false,plan:'free',presence:'online',statusText:'Online',statusEmoji:'✨',statusColor:'#6C5CE7',coins:500,effect:'none'};state.accounts.push(pid);state.messages[pid]=[];save();app()}
function edgeSwipe(){let sx=0,sy=0;qsa('.chatpage,.fullpage,.modalback').forEach(el=>{el.addEventListener('touchstart',e=>{const p=e.touches[0];sx=p.clientX;sy=p.clientY},{passive:true});el.addEventListener('touchend',e=>{const p=e.changedTouches[0];if(sx<20&&p.clientX-sx>88&&Math.abs(p.clientY-sy)<75){if(contextMsg)contextMsg=null;else if(currentMoment)currentMoment=null;else if(overlay)overlay=null;else if(currentChat)currentChat=null;app()}},{passive:true})})}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',()=>{if(state.theme==='system')applyTheme()});
applyTheme();app();
})();
